# https://developer.android.com/ndk/downloads/revision_history
version.ndk=r28b
version.gradle=9.3.1
version.cmdline_tools=13114758
version.sdk_compile=21
version.clang=22
version.openh264=2.6.0
# https://chromiumdash.appspot.com/branches
version.webrtc=152.7977.0.0
version.boost=1.92.0
version.ffmpeg=9.0.1
version.libX11=1.8.13
version.mesa=26.2.1
version.glib=2.89.4
version.e2e_tl=6a46f51bdf5e5052ddae26b61cdf9d4864238442
