# https://developer.android.com/ndk/downloads/revision_history
version.ndk=r28b
version.gradle=9.3.1
version.cmdline_tools=13114758
version.sdk_compile=21
version.clang=22
version.openh264=2.6.0
# https://chromiumdash.appspot.com/branches
version.webrtc=149.7827.3.0
version.boost=1.91.0
version.ffmpeg=8.1.1
version.libX11=1.8.13
version.mesa=26.1.1
version.glib=2.89.0