# Reports the prose keys the generated pages ask for and docsdata does not define.
#   cmake -DDOCS_OUT=<generated dir> -DCONFIG_XML=<docsdata>/config.xml -P CheckDocsCoverage.cmake

if(NOT DEFINED DOCS_OUT OR NOT DEFINED CONFIG_XML)
    message(FATAL_ERROR "docs: DOCS_OUT and CONFIG_XML are required")
endif()
if(NOT EXISTS "${CONFIG_XML}")
    message(FATAL_ERROR "docs: config not found: ${CONFIG_XML}")
endif()

file(READ "${CONFIG_XML}" _cfg)
string(REGEX MATCHALL "<option id=\"[A-Za-z0-9_]+\"" _defined "${_cfg}")
set(_have "")
foreach(_d ${_defined})
    string(REGEX REPLACE "^<option id=\"" "" _d "${_d}")
    string(REGEX REPLACE "\"$" "" _d "${_d}")
    list(APPEND _have "${_d}")
endforeach()

file(GLOB_RECURSE _pages "${DOCS_OUT}/*.xml")
set(_need "")
foreach(_p ${_pages})
    file(READ "${_p}" _c)
    string(REGEX MATCHALL "<config id=\"[A-Za-z0-9_]+\"" _refs "${_c}")
    foreach(_r ${_refs})
        string(REGEX REPLACE "^<config id=\"" "" _r "${_r}")
        string(REGEX REPLACE "\"$" "" _r "${_r}")
        list(APPEND _need "${_r}")
    endforeach()
endforeach()

if(_need)
    list(REMOVE_DUPLICATES _need)
    list(SORT _need)
endif()

set(_missing "")
foreach(_n ${_need})
    list(FIND _have "${_n}" _idx)
    if(_idx LESS 0)
        list(APPEND _missing "${_n}")
    endif()
endforeach()

list(LENGTH _need _n_need)
list(LENGTH _missing _n_missing)
message(STATUS "docs: ${_n_need} keys referenced, ${_n_missing} missing")
foreach(_m ${_missing})
    message(STATUS "  missing: ${_m}")
endforeach()
if(_missing)
    message(FATAL_ERROR "docs: ${_n_missing} prose keys are not defined in ${CONFIG_XML}")
endif()
