include(${CMAKE_CURRENT_LIST_DIR}/NTLParser.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/TemplateEngine.cmake)

function(_docs_docid title out)
    string(REGEX REPLACE "[^A-Za-z0-9]+" "_" _d "${title}")
    string(TOUPPER "${_d}" _d)
    set(${out} "${_d}" PARENT_SCOPE)
endfunction()

function(_docs_load_pages cfg)
    if(NOT EXISTS "${cfg}")
        message(FATAL_ERROR "docs: page map not found: ${cfg}")
    endif()
    file(STRINGS "${cfg}" _lines)
    set(_section "")
    set(_sections "")
    foreach(_l ${_lines})
        string(STRIP "${_l}" _l)
        if(_l STREQUAL "" OR _l MATCHES "^#")
            continue()
        endif()
        if(_l MATCHES "^\\[(.+)\\]$")
            set(_section "${CMAKE_MATCH_1}")
            if(NOT _section STREQUAL "raises")
                list(APPEND _sections "${_section}")
            endif()
            continue()
        endif()
        if(NOT _l MATCHES "^([A-Za-z0-9_.]+)[ \t]*=[ \t]*(.+)$")
            message(FATAL_ERROR "docs: unparsable line in ${cfg}: ${_l}")
        endif()
        set(_key "${CMAKE_MATCH_1}")
        string(STRIP "${CMAKE_MATCH_2}" _val)
        if(_section STREQUAL "raises")
            set_property(GLOBAL PROPERTY DOCS_RAISES_${_key} "${_val}")
        elseif(_section STREQUAL "marks")
            set_property(GLOBAL PROPERTY DOCS_MARK_${_key} "${_val}")
        else()
            set_property(GLOBAL PROPERTY DOCS_SECTION_${_key} "${_section}")
            set_property(GLOBAL PROPERTY DOCS_TITLE_${_key} "${_val}")
        endif()
    endforeach()
    if(_sections)
        list(REMOVE_DUPLICATES _sections)
    endif()
    set_property(GLOBAL PROPERTY DOCS_SECTIONS "${_sections}")
endfunction()

function(_docs_annotate)
    set(_unmapped "")
    set(_pages "")
    get_property(_classes GLOBAL PROPERTY classes)
    foreach(_c ${_classes})
        get_property(_methods GLOBAL PROPERTY ${_c}.methods)
        foreach(_m ${_methods})
            get_property(_name GLOBAL PROPERTY ${_m}.name)
            get_property(_section GLOBAL PROPERTY DOCS_SECTION_${_name})
            if("${_section}" STREQUAL "")
                list(APPEND _unmapped "${_name}")
                continue()
            endif()
            get_property(_title GLOBAL PROPERTY DOCS_TITLE_${_name})
            get_property(_raises GLOBAL PROPERTY DOCS_RAISES_${_name})
            _docs_docid("${_title}" _docid)
            string(REPLACE "," ";" _raises "${_raises}")
            set(_clean "")
            set(_ri 0)
            foreach(_r ${_raises})
                string(STRIP "${_r}" _r)
                if(NOT _r STREQUAL "")
                    set_property(GLOBAL PROPERTY ${_m}.raises.${_ri}.id "${_r}")
                    list(APPEND _clean "${_m}.raises.${_ri}")
                    math(EXPR _ri "${_ri}+1")
                endif()
            endforeach()
            set_property(GLOBAL PROPERTY ${_m}.section "${_section}")
            set_property(GLOBAL PROPERTY ${_m}.title "${_title}")
            set_property(GLOBAL PROPERTY ${_m}.docid "${_docid}")
            set_property(GLOBAL PROPERTY ${_m}.raises "${_clean}")
            get_property(_iscb GLOBAL PROPERTY ${_m}.iscb)
            if(_iscb)
                get_property(_cbtype GLOBAL PROPERTY ${_m}.cbtype)
                get_property(_cbs GLOBAL PROPERTY callbacks)
                foreach(_cb ${_cbs})
                    get_property(_cbn GLOBAL PROPERTY ${_cb}.name)
                    if(_cbn STREQUAL "${_cbtype}")
                        get_property(_cba GLOBAL PROPERTY ${_cb}.cbargs)
                        set_property(GLOBAL PROPERTY ${_m}.cb.cbargs "${_cba}")
                    endif()
                endforeach()
            endif()
            list(APPEND _pages "${_m}")
        endforeach()
    endforeach()
    get_property(_structs GLOBAL PROPERTY structs)
    foreach(_s ${_structs})
        get_property(_name GLOBAL PROPERTY ${_s}.name)
        _flt_snake("${_name}" _snake)
        _docs_docid("${_snake}" _docid)
        set_property(GLOBAL PROPERTY ${_s}.section "Available Types")
        set_property(GLOBAL PROPERTY ${_s}.title "${_name}")
        set_property(GLOBAL PROPERTY ${_s}.docid "${_docid}")
    endforeach()
    get_property(_enums GLOBAL PROPERTY enums)
    foreach(_e ${_enums})
        get_property(_name GLOBAL PROPERTY ${_e}.name)
        _flt_snake("${_name}" _snake)
        _docs_docid("${_snake}" _docid)
        set_property(GLOBAL PROPERTY ${_e}.section "Available Enums")
        set_property(GLOBAL PROPERTY ${_e}.title "${_name}")
        set_property(GLOBAL PROPERTY ${_e}.docid "${_docid}")
    endforeach()
    set_property(GLOBAL PROPERTY docpages "${_pages}")
    set_property(GLOBAL PROPERTY DOCS_UNMAPPED "${_unmapped}")
endfunction()

function(_docs_load_prose cfg)
    if(NOT EXISTS "${cfg}")
        return()
    endif()
    file(STRINGS "${cfg}" _lines)
    foreach(_l ${_lines})
        string(STRIP "${_l}" _l)
        if(_l STREQUAL "" OR _l MATCHES "^#" OR _l MATCHES "^\\[")
            continue()
        endif()
        if(_l MATCHES "^([A-Za-z0-9_.]+)[ \t]*=[ \t]*([A-Za-z0-9_]+)$")
            set_property(GLOBAL PROPERTY DOCS_ALIAS_${CMAKE_MATCH_1} "${CMAKE_MATCH_2}")
        endif()
    endforeach()
endfunction()

function(_docs_mark key out)
    get_property(_raw GLOBAL PROPERTY DOCS_CONFIG_RAW)
    set(${out} "" PARENT_SCOPE)
    if("${_raw}" STREQUAL "")
        return()
    endif()
    if(_raw MATCHES "<option id=\"${key}\">([^<]*)</option>")
        string(STRIP "${CMAKE_MATCH_1}" _v)
        set(${out} "${_v}" PARENT_SCOPE)
    endif()
endfunction()

function(_docs_load_defined cfg)
    set(_have "")
    if(NOT "${cfg}" STREQUAL "" AND EXISTS "${cfg}")
        file(READ "${cfg}" _c)
        set_property(GLOBAL PROPERTY DOCS_CONFIG_RAW "${_c}")
        string(REGEX MATCHALL "<option id=\"[A-Za-z0-9_]+\"" _opts "${_c}")
        foreach(_o ${_opts})
            string(REGEX REPLACE "^<option id=\"" "" _o "${_o}")
            string(REGEX REPLACE "\"$" "" _o "${_o}")
            list(APPEND _have "${_o}")
        endforeach()
        set_property(GLOBAL PROPERTY DOCS_STRICT 1)
    endif()
    set_property(GLOBAL PROPERTY DOCS_DEFINED "${_have}")
endfunction()

function(_docs_has key out)
    get_property(_strict GLOBAL PROPERTY DOCS_STRICT)
    if(NOT _strict)
        set(${out} "1" PARENT_SCOPE)
        return()
    endif()
    get_property(_have GLOBAL PROPERTY DOCS_DEFINED)
    if("${key}" IN_LIST _have)
        set(${out} "1" PARENT_SCOPE)
    else()
        set(${out} "" PARENT_SCOPE)
    endif()
endfunction()

function(_docs_resolve key scope out)
    get_property(_scoped GLOBAL PROPERTY DOCS_ALIAS_${scope}.${key})
    if(NOT "${_scoped}" STREQUAL "")
        set(${out} "${_scoped}" PARENT_SCOPE)
        return()
    endif()
    get_property(_alias GLOBAL PROPERTY DOCS_ALIAS_${key})
    if(NOT "${_alias}" STREQUAL "")
        set(${out} "${_alias}" PARENT_SCOPE)
    else()
        set(${out} "${key}" PARENT_SCOPE)
    endif()
endfunction()

function(_docs_mark_fields coll scope)
    foreach(_f ${coll})
        get_property(_fn GLOBAL PROPERTY ${_f}.name)
        string(TOUPPER "${_fn}" _fu)
        set(_id "${_fu}_DESC")
        get_property(_scoped GLOBAL PROPERTY DOCS_ALIAS_${scope}.${_fn})
        get_property(_alias GLOBAL PROPERTY DOCS_ALIAS_${_id})
        if(NOT "${_scoped}" STREQUAL "")
            set(_id "${_scoped}")
        elseif(NOT "${_alias}" STREQUAL "")
            set(_id "${_alias}")
        endif()
        set_property(GLOBAL PROPERTY ${_f}.descid "${_id}")
        _docs_has("${_id}" _h)
        set_property(GLOBAL PROPERTY ${_f}.hasdesc "${_h}")
    endforeach()
endfunction()

function(_docs_mark_prose)
    get_property(_pages GLOBAL PROPERTY docpages)
    foreach(_m ${_pages})
        get_property(_docid GLOBAL PROPERTY ${_m}.docid)
        get_property(_tl GLOBAL PROPERTY ${_m}.name)
        _docs_resolve("${_docid}_DESC" "${_tl}" _id)
        set_property(GLOBAL PROPERTY ${_m}.descid "${_id}")
        _docs_has("${_id}" _h)
        set_property(GLOBAL PROPERTY ${_m}.hasdesc "${_h}")
        _docs_resolve("${_docid}_DESC2" "${_tl}" _id)
        set_property(GLOBAL PROPERTY ${_m}.desc2id "${_id}")
        _docs_has("${_id}" _h)
        set_property(GLOBAL PROPERTY ${_m}.hasdesc2 "${_h}")
        get_property(_name GLOBAL PROPERTY ${_m}.name)
        set(_anyex "")
        foreach(_lang ${DOCS_LANGUAGES})
            string(TOUPPER "${_lang}" _lu)
            _docs_has("${_docid}_EXAMPLE_${_lu}" _h)
            set_property(GLOBAL PROPERTY ${_m}.hasex${_lang} "${_h}")
            if(_h)
                set(_anyex 1)
            endif()
            _docs_mark("${_docid}_EXAMPLE_${_lu}_MARK" _mark)
            if("${_mark}" STREQUAL "")
                set_property(GLOBAL PROPERTY ${_m}.mark${_lang} "")
            else()
                set_property(GLOBAL PROPERTY ${_m}.mark${_lang} " mark=\"${_mark}\"")
            endif()
        endforeach()
        set_property(GLOBAL PROPERTY ${_m}.hasexample "${_anyex}")
        get_property(_params GLOBAL PROPERTY ${_m}.params)
        _docs_mark_fields("${_params}" "${_name}")
        get_property(_cbargs GLOBAL PROPERTY ${_m}.cb.cbargs)
        _docs_mark_fields("${_cbargs}" "${_name}")
    endforeach()
    get_property(_structs GLOBAL PROPERTY structs)
    foreach(_s ${_structs})
        get_property(_docid GLOBAL PROPERTY ${_s}.docid)
        _docs_resolve("${_docid}_DESC" "${_docid}" _id)
        set_property(GLOBAL PROPERTY ${_s}.descid "${_id}")
        _docs_has("${_id}" _h)
        set_property(GLOBAL PROPERTY ${_s}.hasdesc "${_h}")
        get_property(_fields GLOBAL PROPERTY ${_s}.fields)
        _docs_mark_fields("${_fields}" "${_docid}")
    endforeach()
    get_property(_enums GLOBAL PROPERTY enums)
    foreach(_e ${_enums})
        get_property(_docid GLOBAL PROPERTY ${_e}.docid)
        _docs_resolve("${_docid}_DESC" "${_docid}" _id)
        set_property(GLOBAL PROPERTY ${_e}.descid "${_id}")
        _docs_has("${_id}" _h)
        set_property(GLOBAL PROPERTY ${_e}.hasdesc "${_h}")
        get_property(_members GLOBAL PROPERTY ${_e}.members)
        foreach(_mem ${_members})
            get_property(_disp GLOBAL PROPERTY ${_mem}.disp)
            string(TOUPPER "${_disp}" _du)
            _docs_resolve("${_docid}_${_du}_DESC" "${_docid}" _id)
            set_property(GLOBAL PROPERTY ${_mem}.descid "${_id}")
            _docs_has("${_id}" _h)
            set_property(GLOBAL PROPERTY ${_mem}.hasdesc "${_h}")
        endforeach()
    endforeach()
endfunction()

function(_docs_example_mark path out)
    set(${out} "" PARENT_SCOPE)
    if(NOT EXISTS "${path}")
        return()
    endif()
    file(READ "${path}" _rest)
    set(_emitted 0)
    set(_start 0)
    set(_last 0)
    set(_body "")
    while(NOT "${_rest}" STREQUAL "")
        string(FIND "${_rest}" "\n" _nl)
        if(_nl LESS 0)
            set(_line "${_rest}")
            set(_rest "")
        else()
            string(SUBSTRING "${_rest}" 0 ${_nl} _line)
            math(EXPR _after "${_nl}+1")
            string(SUBSTRING "${_rest}" ${_after} -1 _rest)
        endif()
        if(_line STREQUAL "@@mark@@")
            math(EXPR _start "${_emitted}+1")
        else()
            math(EXPR _emitted "${_emitted}+1")
            string(STRIP "${_line}" _stripped)
            if(NOT "${_stripped}" STREQUAL "")
                set(_last ${_emitted})
            endif()
            string(APPEND _body "${_line}\n")
        endif()
    endwhile()
    string(REGEX REPLACE "\n+$" "" _body "${_body}")
    file(WRITE "${path}" "${_body}")
    if(_start GREATER 0 AND NOT _last LESS _start)
        if(_last EQUAL _start)
            set(${out} "${_start}" PARENT_SCOPE)
        else()
            set(${out} "${_start}-${_last}" PARENT_SCOPE)
        endif()
    endif()
endfunction()

function(_docs_example_marks)
    get_property(_frag GLOBAL PROPERTY config.frag_dir)
    get_property(_pages GLOBAL PROPERTY docpages)
    foreach(_m ${_pages})
        get_property(_docid GLOBAL PROPERTY ${_m}.docid)
        foreach(_lang ${DOCS_LANGUAGES})
            get_property(_hand GLOBAL PROPERTY ${_m}.hasex${_lang})
            _docs_example_mark("${_frag}/example-${_docid}.${_lang}.xml" _mark)
            if(NOT _hand)
                if("${_mark}" STREQUAL "")
                    set_property(GLOBAL PROPERTY ${_m}.mark${_lang} "")
                else()
                    set_property(GLOBAL PROPERTY ${_m}.mark${_lang} " mark=\"${_mark}\"")
                endif()
            endif()
        endforeach()
    endforeach()
endfunction()

function(_docs_write_index out)
    set(_order "Basic Methods" "Stream Methods" "Advanced Methods" "Callbacks" "Available Types" "Available Enums")
    set(_body "")
    get_property(_pages GLOBAL PROPERTY docpages)
    get_property(_structs GLOBAL PROPERTY structs)
    get_property(_enums GLOBAL PROPERTY enums)
    set(_all ${_pages} ${_structs})
    foreach(_e ${_enums})
        get_property(_em GLOBAL PROPERTY ${_e}.emit)
        if(_em)
            list(APPEND _all "${_e}")
        endif()
    endforeach()
    foreach(_section ${_order})
        set(_titles "")
        foreach(_o ${_all})
            get_property(_s GLOBAL PROPERTY ${_o}.section)
            if(_s STREQUAL "${_section}")
                get_property(_t GLOBAL PROPERTY ${_o}.title)
                list(APPEND _titles "${_t}")
            endif()
        endforeach()
        if(NOT _titles)
            continue()
        endif()
        list(SORT _titles)
        string(APPEND _body "    <group basepath=\"NTgCalls/${_section}/\">\n")
        foreach(_t ${_titles})
            string(APPEND _body "      <file>${_t}.xml</file>\n")
        endforeach()
        string(APPEND _body "    </group>\n")
    endforeach()
    file(WRITE "${out}" "${_body}")
endfunction()

if(NOT DEFINED ROOT_DIR)
    message(FATAL_ERROR "docs: ROOT_DIR is required")
endif()
if(NOT DEFINED NTL_OUTPUT_FILE)
    set(NTL_OUTPUT_FILE "${ROOT_DIR}/ntl-output/schema.ntl")
endif()
if(NOT DEFINED DOCS_OUT)
    set(DOCS_OUT "${ROOT_DIR}/docs-output")
endif()

set(DOCS_DIR "${ROOT_DIR}/targets/docs")
set(DOCS_LANGUAGES python c node java rust)

if(EXISTS "${DOCS_OUT}")
    file(REMOVE_RECURSE "${DOCS_OUT}")
endif()
file(MAKE_DIRECTORY "${DOCS_OUT}")

set_property(GLOBAL PROPERTY config.root "${ROOT_DIR}")
set_property(GLOBAL PROPERTY config.docs_out "${DOCS_OUT}")
set_property(GLOBAL PROPERTY config.frag_dir "${DOCS_OUT}/.fragments")
set_property(GLOBAL PROPERTY config.banner "<!-- @generated from schema.ntl / DO NOT EDIT -->")

ntl_parse(${NTL_OUTPUT_FILE})
_docs_load_pages("${DOCS_DIR}/pages.cfg")
_docs_annotate()
if(NOT DEFINED CONFIG_XML)
    set(CONFIG_XML "")
endif()
_docs_load_prose("${DOCS_DIR}/prose.cfg")
_docs_load_defined("${CONFIG_XML}")
_docs_mark_prose()

file(GLOB _tpls "${DOCS_DIR}/*.tpl")
foreach(_t ${_tpls})
    if(NOT _t MATCHES "/9[0-9]-[^/]*\\.tpl$")
        render_template("${_t}")
    endif()
endforeach()
_docs_example_marks()
foreach(_t ${_tpls})
    if(_t MATCHES "/9[0-9]-[^/]*\\.tpl$")
        render_template("${_t}")
    endif()
endforeach()

file(REMOVE_RECURSE "${DOCS_OUT}/.fragments")
_docs_write_index("${DOCS_OUT}/files-list.xml")

get_property(_unmapped GLOBAL PROPERTY DOCS_UNMAPPED)
if(_unmapped)
    list(JOIN _unmapped ", " _u)
    message(WARNING "docs: methods missing from pages.cfg and not documented: ${_u}")
endif()
