include(${CMAKE_CURRENT_LIST_DIR}/NTLParser.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/TemplateEngine.cmake)

function(_purge_generated dir)
    if(NOT EXISTS "${dir}")
        return()
    endif()
    file(GLOB_RECURSE _files "${dir}/*")
    foreach(_f ${_files})
        if(NOT IS_DIRECTORY "${_f}" AND NOT _f MATCHES "\\.tpl$")
            file(READ "${_f}" _head LIMIT 96)
            if(_head MATCHES "@generated")
                file(REMOVE "${_f}")
            endif()
        endif()
    endforeach()
endfunction()

function(_write_gitignore root)
    file(GLOB_RECURSE _files "${root}/*")
    set(_lines "/.gitignore")
    foreach(_f ${_files})
        if(NOT IS_DIRECTORY "${_f}" AND NOT _f MATCHES "\\.tpl$")
            file(READ "${_f}" _head LIMIT 96)
            if(_head MATCHES "@generated")
                file(RELATIVE_PATH _rel "${root}" "${_f}")
                list(APPEND _lines "/${_rel}")
            endif()
        endif()
    endforeach()
    list(JOIN _lines "\n" _content)
    file(WRITE "${root}/.gitignore" "${_content}\n")
endfunction()

if(NOT DEFINED BINDING)
    set(BINDING "python")
endif()

_purge_generated("${ROOT_DIR}/targets")

set(GEN_SOURCES "")
set(GEN_INCLUDES "")

file(GLOB_RECURSE _tpls "${ROOT_DIR}/targets/${BINDING}/*.tpl")
if(_tpls)
    set_property(GLOBAL PROPERTY config.root "${ROOT_DIR}")
    set_property(GLOBAL PROPERTY config.banner "// @generated from schema/ntgcalls.ntl -- DO NOT EDIT")
    ntl_parse(${NTL_OUTPUT_FILE})
    foreach(_t ${_tpls})
        render_template("${_t}")
    endforeach()
endif()

file(GLOB GEN_SOURCES "${ROOT_DIR}/targets/${BINDING}/*.cpp" "${ROOT_DIR}/targets/${BINDING}/*.cc")
if(EXISTS "${ROOT_DIR}/targets/${BINDING}/support")
    list(APPEND GEN_INCLUDES "${ROOT_DIR}/targets/${BINDING}/support")
endif()

_write_gitignore("${ROOT_DIR}/targets")
