include(${CMAKE_CURRENT_LIST_DIR}/NTLGenerator.cmake)

set(NTL_OUTPUT_DIR "${ROOT_DIR}/ntl-output")
set(NTL_OUTPUT_FILE "${NTL_OUTPUT_DIR}/schema.ntl")

if (EXISTS "${NTL_OUTPUT_DIR}")
    file(REMOVE_RECURSE "${NTL_OUTPUT_DIR}")
endif()
file(MAKE_DIRECTORY "${NTL_OUTPUT_DIR}")

set(API_HPP "")
set(API_CPP "")
set(ALIASES "")
set(STRUCT_HEADERS "")
set(EXC_HEADERS "")
file(STRINGS "${ROOT_DIR}/targets/sources.ntlgen" _srclines)
foreach(l ${_srclines})
    if(NOT l MATCHES "^([a-z]+)[ \t]*=[ \t]*(.+[^ \t])[ \t]*$")
        continue()
    endif()
    set(_k "${CMAKE_MATCH_1}")
    set(_v "${ROOT_DIR}/${CMAKE_MATCH_2}")
    if(_k STREQUAL "api")
        set(API_HPP "${_v}")
    elseif(_k STREQUAL "source")
        set(API_CPP "${_v}")
    elseif(_k STREQUAL "aliases")
        set(ALIASES "${_v}")
    elseif(_k STREQUAL "types")
        file(GLOB _g "${_v}")
        list(APPEND STRUCT_HEADERS ${_g})
    elseif(_k STREQUAL "errors")
        list(APPEND EXC_HEADERS "${_v}")
    endif()
endforeach()

gen_ntl("${API_HPP}" "${API_CPP}" "${ALIASES}" "${STRUCT_HEADERS}" "${EXC_HEADERS}" "${NTL_OUTPUT_FILE}")
