function(_crc32 s out)
    string(HEX "${s}" hx)
    string(LENGTH "${hx}" hl)
    set(crc 4294967295)
    set(i 0)
    while(i LESS hl)
        string(SUBSTRING "${hx}" ${i} 2 byte)
        math(EXPR b "0x${byte}")
        math(EXPR crc "${crc} ^ ${b}")
        foreach(k RANGE 7)
            math(EXPR lsb "${crc} & 1")
            if(lsb)
                math(EXPR crc "(${crc} >> 1) ^ 3988292384")
            else()
                math(EXPR crc "${crc} >> 1")
            endif()
        endforeach()
        math(EXPR i "${i}+2")
    endwhile()
    math(EXPR crc "(${crc} ^ 4294967295) & 4294967295")
    set(hexout "")
    foreach(n RANGE 7)
        math(EXPR sh "4*(7-${n})")
        math(EXPR nib "(${crc} >> ${sh}) & 15")
        string(SUBSTRING "0123456789abcdef" ${nib} 1 c)
        string(APPEND hexout "${c}")
    endforeach()
    set(${out} "${hexout}" PARENT_SCOPE)
endfunction()

function(_line_crc rawline out)
    string(REGEX REPLACE "//.*$" "" c "${rawline}")
    string(REGEX REPLACE ";[ \t]*$" "" c "${c}")
    string(REGEX REPLACE "[ \t]+" " " c "${c}")
    string(STRIP "${c}" c)
    _crc32("${c}" id)
    set(${out} "${id}" PARENT_SCOPE)
endfunction()

function(_with_id rawline out)
    _line_crc("${rawline}" id)
    string(STRIP "${rawline}" r)
    if(r MATCHES "^([^ ;]+)(.*)$")
        set(${out} "${CMAKE_MATCH_1}#${id}${CMAKE_MATCH_2}" PARENT_SCOPE)
    else()
        set(${out} "${r}" PARENT_SCOPE)
    endif()
endfunction()

function(_gentl_load_aliases alias_file)
    file(STRINGS "${alias_file}" alines)
    foreach(l ${alines})
        if(NOT l MATCHES "^alias[ \t]+([^ \t]+)[ \t]*=[ \t]*([^ \t]+)[ \t]*$")
            continue()
        endif()
        set(lhs "${CMAKE_MATCH_1}")
        set(rhs "${CMAKE_MATCH_2}")
        if(lhs MATCHES "^(.+::)\\*$")
            set_property(GLOBAL APPEND PROPERTY ALIAS_RULES "P|${CMAKE_MATCH_1}|${rhs}")
        else()
            set_property(GLOBAL APPEND PROPERTY ALIAS_RULES "E|${lhs}|${rhs}")
        endif()
    endforeach()
endfunction()

function(_alias_resolve q out)
    get_property(rules GLOBAL PROPERTY ALIAS_RULES)
    foreach(r ${rules})
        string(REPLACE "|" ";" rr "${r}")
        list(GET rr 0 kind)
        list(GET rr 1 m)
        list(GET rr 2 rep)
        if(kind STREQUAL "E" AND m STREQUAL "${q}")
            set(${out} "${rep}" PARENT_SCOPE)
            return()
        endif()
    endforeach()
    foreach(r ${rules})
        string(REPLACE "|" ";" rr "${r}")
        list(GET rr 0 kind)
        list(GET rr 1 m)
        list(GET rr 2 rep)
        if(kind STREQUAL "P")
            string(LENGTH "${m}" plen)
            string(SUBSTRING "${q}" 0 ${plen} head)
            if(head STREQUAL "${m}")
                string(SUBSTRING "${q}" ${plen} -1 rest)
                string(REPLACE "*" "${rest}" name "${rep}")
                set(${out} "${name}" PARENT_SCOPE)
                return()
            endif()
        endif()
    endforeach()
    string(REGEX REPLACE ".*::" "" base "${q}")
    set(${out} "${base}" PARENT_SCOPE)
endfunction()

function(_gentl_scan_ns headers)
    foreach(h ${headers})
        if(NOT EXISTS "${h}")
            continue()
        endif()
        file(READ "${h}" src)
        string(REGEX REPLACE "//[^\n]*" "" src "${src}")
        string(REGEX REPLACE "[ \t\r\n]+" " " flat "${src}")
        string(ASCII 1 SC)
        string(REPLACE ";" "${SC}" flat "${flat}")
        string(REGEX MATCHALL "namespace +[A-Za-z0-9_:]+::[A-Za-z0-9_]+ [^@]*" chunks "${flat}")
        foreach(ck ${chunks})
            if(ck MATCHES "namespace +([A-Za-z0-9_:]+) ")
                string(REGEX REPLACE "^(ntgcalls|wrtc|telegram)::" "" ns "${CMAKE_MATCH_1}")
                string(REGEX REPLACE "::.*$" "" ns "${ns}")
                string(REGEX MATCHALL "(struct|class) +[A-Za-z0-9_]+" tds "${ck}")
                foreach(td ${tds})
                    if(td MATCHES "(struct|class) +([A-Za-z0-9_]+)$")
                        get_property(_ns_existing GLOBAL PROPERTY NSMAP_${CMAKE_MATCH_2})
                        if("${_ns_existing}" STREQUAL "")
                            set_property(GLOBAL PROPERTY NSMAP_${CMAKE_MATCH_2} "${ns}")
                        endif()
                    endif()
                endforeach()
            endif()
        endforeach()
    endforeach()
endfunction()

function(_gentl_scan_cbargs cpp)
    if(NOT EXISTS "${cpp}")
        return()
    endif()
    file(READ "${cpp}" src)
    string(REGEX REPLACE "//[^\n]*" "" src "${src}")
    string(REGEX REPLACE "[ \t\r\n]+" " " flat "${src}")
    string(REGEX MATCHALL "->on_[a-z0-9_]+|[a-z_]*_callback_ *\\([^;]*" toks "${flat}")
    set(pending "")
    foreach(tok ${toks})
        if(tok MATCHES "^->(on_[a-z0-9_]+)$")
            set(pending "${CMAKE_MATCH_1}")
        elseif(NOT "${pending}" STREQUAL "" AND tok MATCHES "_callback_ *\\((.*)$")
            set(argstr "${CMAKE_MATCH_1}")
            string(REGEX REPLACE "\\).*$" "" argstr "${argstr}")
            set(names "")
            string(REPLACE "," ";" al "${argstr}")
            foreach(a ${al})
                if(a MATCHES "([A-Za-z_][A-Za-z0-9_]*)[^A-Za-z0-9_]*$")
                    list(APPEND names "${CMAKE_MATCH_1}")
                endif()
            endforeach()
            set_property(GLOBAL PROPERTY CBARGS_${pending} "${names}")
            set(pending "")
        endif()
    endforeach()
endfunction()

function(_nsify base out)
    get_property(ns GLOBAL PROPERTY NSMAP_${base})
    if(NOT "${ns}" STREQUAL "")
        set(${out} "${ns}.${base}" PARENT_SCOPE)
    else()
        set(${out} "${base}" PARENT_SCOPE)
    endif()
endfunction()

function(_split_top str sep out)
    string(LENGTH "${str}" n)
    set(depth 0)
    set(cur "")
    set(res "")
    set(i 0)
    while(i LESS n)
        string(SUBSTRING "${str}" ${i} 1 c)
        if(c STREQUAL "<")
            math(EXPR depth "${depth}+1")
        elseif(c STREQUAL ">")
            math(EXPR depth "${depth}-1")
        endif()
        if(c STREQUAL "${sep}" AND depth EQUAL 0)
            list(APPEND res "${cur}")
            set(cur "")
        else()
            string(APPEND cur "${c}")
        endif()
        math(EXPR i "${i}+1")
    endwhile()
    string(STRIP "${cur}" cur)
    if(NOT cur STREQUAL "")
        list(APPEND res "${cur}")
    endif()
    set(${out} "${res}" PARENT_SCOPE)
endfunction()

function(_cpp_to_tl t out)
    string(STRIP "${t}" t)
    string(REGEX REPLACE "^const +" "" t "${t}")
    string(REGEX REPLACE " *&$" "" t "${t}")
    string(STRIP "${t}" t)
    if(t MATCHES "^std::optional<(.+)>$")
        _cpp_to_tl("${CMAKE_MATCH_1}" r)
        set(${out} "${r}" PARENT_SCOPE)
        return()
    endif()
    if(t MATCHES "^std::vector<(.+)>$")
        _cpp_to_tl("${CMAKE_MATCH_1}" r)
        set(${out} "Vector<${r}>" PARENT_SCOPE)
        return()
    endif()
    if(t MATCHES "^std::(unordered_map|map)<(.+)>$")
        _split_top("${CMAKE_MATCH_2}" "," parts)
        list(GET parts 0 k)
        list(GET parts 1 v)
        _cpp_to_tl("${k}" kr)
        _cpp_to_tl("${v}" vr)
        set(${out} "Map<${kr}, ${vr}>" PARENT_SCOPE)
        return()
    endif()
    if(t STREQUAL "bytes::binary")
        set(${out} "bytes" PARENT_SCOPE)
        return()
    endif()
    if(t STREQUAL "int64_t")
        set(${out} "long" PARENT_SCOPE)
        return()
    endif()
    if(t STREQUAL "uint64_t" OR t STREQUAL "size_t")
        set(${out} "ulong" PARENT_SCOPE)
        return()
    endif()
    if(t STREQUAL "int8_t")
        set(${out} "int8" PARENT_SCOPE)
        return()
    endif()
    if(t STREQUAL "uint8_t")
        set(${out} "uint8" PARENT_SCOPE)
        return()
    endif()
    if(t STREQUAL "int16_t")
        set(${out} "int16" PARENT_SCOPE)
        return()
    endif()
    if(t STREQUAL "uint16_t")
        set(${out} "uint16" PARENT_SCOPE)
        return()
    endif()
    if(t STREQUAL "uint32_t")
        set(${out} "uint" PARENT_SCOPE)
        return()
    endif()
    if(t STREQUAL "int32_t" OR t STREQUAL "int")
        set(${out} "int" PARENT_SCOPE)
        return()
    endif()
    if(t STREQUAL "bool")
        set(${out} "bool" PARENT_SCOPE)
        return()
    endif()
    if(t STREQUAL "double" OR t STREQUAL "float")
        set(${out} "double" PARENT_SCOPE)
        return()
    endif()
    if(t STREQUAL "std::string")
        set(${out} "string" PARENT_SCOPE)
        return()
    endif()
    if(t STREQUAL "void")
        set(${out} "Void" PARENT_SCOPE)
        return()
    endif()
    string(REGEX REPLACE "^(wrtc|webrtc|ntgcalls|telegram)::" "" tk "${t}")
    if(tk MATCHES "^([a-z][a-z0-9_]*)::(.+)$")
        set(nsh "${CMAKE_MATCH_1}")
        _alias_resolve("${CMAKE_MATCH_2}" base)
        set(${out} "${nsh}.${base}" PARENT_SCOPE)
    else()
        _alias_resolve("${tk}" base)
        _nsify("${base}" nb)
        set(${out} "${nb}" PARENT_SCOPE)
    endif()
endfunction()

function(_enum_distinct mname ename out)
    if(mname MATCHES "^k([A-Z].*)$")
        set(m "${CMAKE_MATCH_1}")
    else()
        set(m "${mname}")
    endif()
    string(REPLACE "_" "" m "${m}")
    if(m MATCHES "^${ename}(.+)$")
        set(m "${CMAKE_MATCH_1}")
    endif()
    set(${out} "${m}" PARENT_SCOPE)
endfunction()

function(_camel in out)
    string(REPLACE "_" ";" parts "${in}")
    set(r "")
    set(first 1)
    foreach(p ${parts})
        if(p STREQUAL "")
            continue()
        endif()
        if(first)
            set(r "${p}")
            set(first 0)
        else()
            string(SUBSTRING "${p}" 0 1 h)
            string(TOUPPER "${h}" h)
            string(SUBSTRING "${p}" 1 -1 t)
            string(APPEND r "${h}${t}")
        endif()
    endforeach()
    set(${out} "${r}" PARENT_SCOPE)
endfunction()

function(_conv_params argstr out)
    _split_top("${argstr}" "," plist)
    set(res "")
    foreach(p ${plist})
        string(STRIP "${p}" p)
        if(p STREQUAL "")
            continue()
        endif()
        if(p MATCHES "^(.+[ &*])([A-Za-z0-9_]+)$")
            set(ptype "${CMAKE_MATCH_1}")
            set(pname "${CMAKE_MATCH_2}")
            _cpp_to_tl("${ptype}" tt)
            string(APPEND res " ${pname}:${tt}")
        endif()
    endforeach()
    string(STRIP "${res}" res)
    set(${out} "${res}" PARENT_SCOPE)
endfunction()

function(_qualify_ctor_type t sname rev out)
    string(STRIP "${t}" t)
    if(t MATCHES "^(std::optional|std::vector)<(.+)>$")
        _qualify_ctor_type("${CMAKE_MATCH_2}" "${sname}" "${rev}" _in)
        set(${out} "${CMAKE_MATCH_1}<${_in}>" PARENT_SCOPE)
        return()
    endif()
    if(t MATCHES "bytes::(binary|vector)" OR t MATCHES "^(u?int(8|16|32|64)_t|int|size_t|bool|double|float|std::string)$")
        set(${out} "${t}" PARENT_SCOPE)
        return()
    endif()
    if(t MATCHES "^[A-Za-z0-9_]+$")
        get_property(_eq GLOBAL PROPERTY ENUMQUAL_${sname}__${t})
        if(NOT "${_eq}" STREQUAL "")
            set(${out} "${rev}::${t}" PARENT_SCOPE)
            return()
        endif()
    endif()
    if(t MATCHES "^([A-Za-z0-9_]+)(::.*)?$")
        set(_head "${CMAKE_MATCH_1}")
        set(_rest "${CMAKE_MATCH_2}")
        get_property(_cq GLOBAL PROPERTY CPPQ_${_head})
        if(NOT "${_cq}" STREQUAL "")
            set(${out} "${_cq}${_rest}" PARENT_SCOPE)
            return()
        endif()
    endif()
    set(${out} "${t}" PARENT_SCOPE)
endfunction()

function(_ctor_args ob sname rev out)
    set(res "")
    if(NOT ob MATCHES "[^~A-Za-z0-9_]${sname} *\\(([^)]+)\\)")
        set(${out} "" PARENT_SCOPE)
        return()
    endif()
    _split_top("${CMAKE_MATCH_1}" "," plist)
    foreach(p ${plist})
        string(REGEX REPLACE " *=.*$" "" p "${p}")
        string(STRIP "${p}" p)
        if(p STREQUAL "" OR NOT p MATCHES "^(.+[ &*])([A-Za-z0-9_]+)$")
            continue()
        endif()
        set(ptype "${CMAKE_MATCH_1}")
        set(pname "${CMAKE_MATCH_2}")
        string(STRIP "${ptype}" ptype)
        string(REGEX REPLACE "^const +" "" ptype "${ptype}")
        string(REGEX REPLACE "[ *&]+$" "" ptype "${ptype}")
        string(STRIP "${ptype}" ptype)
        _qualify_ctor_type("${ptype}" "${sname}" "${rev}" ptype)
        if(NOT res STREQUAL "")
            string(APPEND res ",")
        endif()
        string(APPEND res "${pname}|${ptype}")
    endforeach()
    set(${out} "${res}" PARENT_SCOPE)
endfunction()

function(_cb_fields argstr onname out)
    get_property(realnames GLOBAL PROPERTY CBARGS_${onname})
    list(LENGTH realnames rn)
    _split_top("${argstr}" "," plist)
    set(res "")
    set(idx 0)
    foreach(p ${plist})
        string(STRIP "${p}" p)
        if(p STREQUAL "")
            continue()
        endif()
        _cpp_to_tl("${p}" tt)
        if(NOT idx LESS rn)
            message(FATAL_ERROR "GenTl: no param name for ${onname} arg #${idx} (type ${tt}). "
                "Expose it via a matching <name>_callback_(...) invocation in ntgcalls.cpp.")
        endif()
        list(GET realnames ${idx} nm)
        string(APPEND res " ${nm}:${tt}")
        math(EXPR idx "${idx}+1")
    endforeach()
    string(STRIP "${res}" res)
    set(${out} "${res}" PARENT_SCOPE)
endfunction()

function(_gen_functions hpp fns_out cbs_out)
    file(READ "${hpp}" src)
    string(REGEX REPLACE "//[^\n]*" "" src "${src}")
    string(REGEX REPLACE "[ \t\r\n]+" " " flat "${src}")
    string(REGEX MATCHALL "[^;]+" stmts "${flat}")

    if(NOT flat MATCHES "class +([A-Za-z0-9_]+)[^{}]*\\{[^{}]*\\[\\[ntg::async\\]\\]")
        message(FATAL_ERROR "GenTl: cannot find the API class (class ... { [[ntg::async]] ... }) in ${hpp}")
    endif()
    set(cls "${CMAKE_MATCH_1}")
    set(clsns "")
    if(flat MATCHES "namespace +([A-Za-z0-9_:]+)")
        set(clsns "${CMAKE_MATCH_1}")
    endif()
    if(NOT "${clsns}" STREQUAL "")
        set_property(GLOBAL APPEND PROPERTY CPPDEFS "${cls}=${clsns}::${cls}")
    else()
        set_property(GLOBAL APPEND PROPERTY CPPDEFS "${cls}=${cls}")
    endif()

    set(fns "")
    set(cbs "")
    foreach(s ${stmts})
        if(s MATCHES "void +(on[A-Za-z0-9_]+) *\\( *const std::function<void\\((.*)\\)> *& *callback *\\)")
            set(name "${CMAKE_MATCH_1}")
            set(cbargs "${CMAKE_MATCH_2}")
            string(REGEX REPLACE "^on_" "" _cbbase "${name}")
            _camel("${_cbbase}" _cbbase)
            _pascal1("${_cbbase}" _cbbase)
            set(cbtype "${_cbbase}Callback")
            _camel("${name}" _mtl)
            string(APPEND fns "${cls}.${_mtl} callback:Function<${cbtype}> = Void;\n")
            _cb_fields("${cbargs}" "${name}" cbf)
            string(SUBSTRING "${cbtype}" 0 1 h)
            string(TOLOWER "${h}" h)
            string(SUBSTRING "${cbtype}" 1 -1 t)
            if(cbf STREQUAL "")
                string(APPEND cbs "${h}${t} = ${cbtype};\n")
            else()
                string(APPEND cbs "${h}${t} ${cbf} = ${cbtype};\n")
            endif()
        elseif(s MATCHES "\\[\\[ntg::async\\]\\] +(.+) +([A-Za-z0-9_]+) *\\((.*)\\)")
            set(ret "${CMAKE_MATCH_1}")
            set(name "${CMAKE_MATCH_2}")
            set(args "${CMAKE_MATCH_3}")
            _cpp_to_tl("${ret}" tr)
            _conv_params("${args}" pa)
            _camel("${name}" _mtl)
            if(pa STREQUAL "")
                string(APPEND fns "${cls}.${_mtl} = Async<${tr}>;\n")
            else()
                string(APPEND fns "${cls}.${_mtl} ${pa} = Async<${tr}>;\n")
            endif()
        elseif(s MATCHES "static +([A-Za-z0-9_:<>]+) +([A-Za-z0-9_]+) *\\((.*)\\)")
            set(ret "${CMAKE_MATCH_1}")
            set(name "${CMAKE_MATCH_2}")
            set(args "${CMAKE_MATCH_3}")
            _cpp_to_tl("${ret}" tr)
            _conv_params("${args}" pa)
            _camel("${name}" _mtl)
            if(pa STREQUAL "")
                string(APPEND fns "${cls}.${_mtl} = Static<${tr}>;\n")
            else()
                string(APPEND fns "${cls}.${_mtl} ${pa} = Static<${tr}>;\n")
            endif()
        endif()
    endforeach()
    set(${fns_out} "${fns}" PARENT_SCOPE)
    set(${cbs_out} "${cbs}" PARENT_SCOPE)
endfunction()

function(_first_lower in out)
    string(SUBSTRING "${in}" 0 1 h)
    string(TOLOWER "${h}" h)
    string(SUBSTRING "${in}" 1 -1 t)
    set(${out} "${h}${t}" PARENT_SCOPE)
endfunction()

function(_camel_first in out)
    string(LENGTH "${in}" n)
    set(run 0)
    while(run LESS n)
        string(SUBSTRING "${in}" ${run} 1 c)
        string(TOUPPER "${c}" cu)
        string(TOLOWER "${c}" cl)
        if(c STREQUAL cl OR NOT c STREQUAL cu)
            break()
        endif()
        math(EXPR run "${run}+1")
    endwhile()
    if(run LESS 2)
        _first_lower("${in}" r)
    elseif(run EQUAL 2)
        string(SUBSTRING "${in}" 0 2 acr)
        string(TOLOWER "${acr}" acr)
        string(SUBSTRING "${in}" 2 -1 rest)
        set(r "${acr}${rest}")
    elseif(run LESS n)
        math(EXPR keep "${run}-1")
        string(SUBSTRING "${in}" 0 ${keep} acr)
        string(TOLOWER "${acr}" acr)
        string(SUBSTRING "${in}" ${keep} -1 rest)
        set(r "${acr}${rest}")
    else()
        string(TOLOWER "${in}" r)
    endif()
    set(${out} "${r}" PARENT_SCOPE)
endfunction()

function(_gen_enums headers out)
    set(res "")
    foreach(h ${headers})
        if(NOT EXISTS "${h}")
            continue()
        endif()
        file(READ "${h}" src)
        string(REGEX REPLACE "//[^\n]*" "" src "${src}")
        string(REGEX REPLACE "[ \t\r\n]+" " " flat "${src}")
        string(REGEX MATCHALL "namespace +[A-Za-z0-9_:]+|(struct|class) +[A-Za-z0-9_]+|enum( +class)? +[A-Za-z0-9_]+ *\\{[^}]*\\}|[{}]" toks "${flat}")
        set(frames "")
        set(pending "")
        foreach(tok ${toks})
            if(tok MATCHES "^namespace +([A-Za-z0-9_:]+)$")
                set(pending "N|${CMAKE_MATCH_1}")
            elseif(tok MATCHES "^(struct|class) +([A-Za-z0-9_]+)$")
                set(pending "C|${CMAKE_MATCH_2}")
            elseif(tok STREQUAL "{")
                if(pending STREQUAL "")
                    list(APPEND frames "O")
                else()
                    list(APPEND frames "${pending}")
                endif()
                set(pending "")
            elseif(tok STREQUAL "}")
                list(LENGTH frames fl)
                if(fl GREATER 0)
                    list(REMOVE_AT frames -1)
                endif()
            elseif(tok MATCHES "^enum( +class)? +([A-Za-z0-9_]+) *\\{([^}]*)\\}$")
                set(ename "${CMAKE_MATCH_2}")
                set(body "${CMAKE_MATCH_3}")
                set(classpath "")
                set(curns "")
                set(nsfull "")
                foreach(fr ${frames})
                    if(fr MATCHES "^C\\|(.+)$")
                        if(classpath STREQUAL "")
                            set(classpath "${CMAKE_MATCH_1}")
                        else()
                            set(classpath "${classpath}::${CMAKE_MATCH_1}")
                        endif()
                    elseif(fr MATCHES "^N\\|(.+)$")
                        set(nsraw "${CMAKE_MATCH_1}")
                        if(nsfull STREQUAL "")
                            set(nsfull "${nsraw}")
                        else()
                            set(nsfull "${nsfull}::${nsraw}")
                        endif()
                        if(nsraw MATCHES "::")
                            string(REGEX REPLACE "^.*::" "" curns "${nsraw}")
                        endif()
                    endif()
                endforeach()
                _alias_resolve("${classpath}::${ename}" tlname)
                if(NOT curns STREQUAL "")
                    set(ftype "${curns}.${tlname}")
                else()
                    _nsify("${tlname}" ftype)
                endif()

                get_property(_seenq GLOBAL PROPERTY CPPQ_${tlname})
                if(NOT "${_seenq}" STREQUAL "")
                    continue()
                endif()

                set(cppq "${ename}")
                if(NOT classpath STREQUAL "")
                    set(cppq "${classpath}::${cppq}")
                endif()
                if(NOT nsfull STREQUAL "")
                    set(cppq "${nsfull}::${cppq}")
                endif()
                set_property(GLOBAL APPEND PROPERTY CPPDEFS "${tlname}=${cppq}")
                set_property(GLOBAL PROPERTY CPPQ_${tlname} "${cppq}")

                string(REGEX REPLACE "^.*::" "" _lastcls "${classpath}")
                set_property(GLOBAL PROPERTY ENUMQUAL_${_lastcls}__${ename} "${ftype}")
                set_property(GLOBAL PROPERTY ENUMBARE_${ename} "${ftype}")
                string(REGEX REPLACE "[ \t]+" "" body "${body}")
                string(REPLACE "," ";" items "${body}")
                set(counter 0)
                foreach(it ${items})
                    if(it MATCHES "^([A-Za-z0-9_]+)(=(.+))?$")
                        set(mname "${CMAKE_MATCH_1}")
                        set(_mval "${CMAKE_MATCH_3}")
                        if(_mval MATCHES "^[0-9a-fA-FxX <>|&+*/()~-]+$")
                            math(EXPR counter "${_mval}")
                        endif()
                        _enum_distinct("${mname}" "${ename}" cc)
                        set_property(GLOBAL APPEND PROPERTY CPPDEFS "${tlname}.${cc}=${mname}")
                        string(APPEND res "${cc} = Enum<${ftype}, ${counter}>;\n")
                        math(EXPR counter "${counter}+1")
                    endif()
                endforeach()
                string(APPEND res "\n")
            endif()
        endforeach()
    endforeach()
    set(${out} "${res}" PARENT_SCOPE)
endfunction()

function(_find_matching_brace s start out)
    string(LENGTH "${s}" n)
    set(depth 0)
    set(i ${start})
    while(i LESS n)
        string(SUBSTRING "${s}" ${i} 1 c)
        if(c STREQUAL "{")
            math(EXPR depth "${depth}+1")
        elseif(c STREQUAL "}")
            math(EXPR depth "${depth}-1")
            if(depth EQUAL 0)
                set(${out} ${i} PARENT_SCOPE)
                return()
            endif()
        endif()
        math(EXPR i "${i}+1")
    endwhile()
    set(${out} -1 PARENT_SCOPE)
endfunction()

function(_field_type ftype chain out)
    if(ftype MATCHES "^[A-Z][A-Za-z0-9_]*$")
        foreach(cls ${chain})
            get_property(q GLOBAL PROPERTY ENUMQUAL_${cls}__${ftype})
            if(NOT "${q}" STREQUAL "")
                set(${out} "${q}" PARENT_SCOPE)
                return()
            endif()
        endforeach()
        get_property(b GLOBAL PROPERTY ENUMBARE_${ftype})
        if(NOT "${b}" STREQUAL "")
            set(${out} "${b}" PARENT_SCOPE)
            return()
        endif()
    endif()
    _cpp_to_tl("${ftype}" tt)
    set(${out} "${tt}" PARENT_SCOPE)
endfunction()

function(_struct_own_fields body sc out chain)
    string(ASCII 2 SC2)
    string(REPLACE "${sc}" ";" body "${body}")
    string(REGEX REPLACE "(public|private|protected) *:" " " body "${body}")
    string(REGEX MATCHALL "[^;]+" decls "${body}")
    set(fields "")
    foreach(d ${decls})
        string(STRIP "${d}" d)
        if(d STREQUAL "" OR d MATCHES "[(){}]"
           OR d MATCHES "^(public|private|protected|using|friend|static|typedef|template|struct|class|enum|virtual|inline|explicit|operator|~)")
            continue()
        endif()
        string(REGEX REPLACE "^(const|mutable) +" "" d "${d}")
        string(REGEX REPLACE " *= *[^,]*" "" d "${d}")
        string(STRIP "${d}" d)
        if(d MATCHES "^([^ ]+) +([A-Za-z0-9_][A-Za-z0-9_, ]*)$")
            set(ftype "${CMAKE_MATCH_1}")
            _field_type("${ftype}" "${chain}" tt)
            list(GET chain 0 _sname)
            string(REPLACE "," ";" fnl "${CMAKE_MATCH_2}")
            foreach(fn ${fnl})
                string(STRIP "${fn}" fn)
                string(APPEND fields " ${fn}:${tt}")
                set_property(GLOBAL APPEND PROPERTY SDEF_${_sname}_FIELDCPP "${fn}=${fn}")
                set_property(GLOBAL APPEND PROPERTY SDEF_${_sname}_MEMBERS "${fn}${SC2}${tt}${SC2}${fn}${SC2}${ftype}")
            endforeach()
        endif()
    endforeach()
    string(STRIP "${fields}" fields)
    set(${out} "${fields}" PARENT_SCOPE)
endfunction()

function(_scan_structs flat sc pathlist filens)
    while(TRUE)
        string(REGEX MATCH "(struct|class) +([A-Za-z0-9_]+)([^{;]*)\\{" m "${flat}")
        if(m STREQUAL "")
            return()
        endif()
        set(sname "${CMAKE_MATCH_2}")
        set(bases "${CMAKE_MATCH_3}")
        string(FIND "${flat}" "${m}" mpos)
        string(LENGTH "${m}" mlen)
        math(EXPR bracepos "${mpos}+${mlen}-1")
        _find_matching_brace("${flat}" ${bracepos} endpos)
        if(endpos LESS 0)
            return()
        endif()
        math(EXPR bstart "${bracepos}+1")
        math(EXPR blen "${endpos}-${bstart}")
        string(SUBSTRING "${flat}" ${bstart} ${blen} body)

        if("${pathlist}" STREQUAL "")
            set(chain "${sname}")
        else()
            set(chain "${sname};${pathlist}")
        endif()
        _scan_structs("${body}" "${sc}" "${chain}" "${filens}")

        get_property(seen GLOBAL PROPERTY SDEF_SEEN_${sname})
        if("${seen}" STREQUAL "")
            set_property(GLOBAL PROPERTY SDEF_SEEN_${sname} "1")
            set_property(GLOBAL APPEND PROPERTY SDEF_NAMES "${sname}")
            set(rev "")
            foreach(p ${chain})
                if(rev STREQUAL "")
                    set(rev "${p}")
                else()
                    set(rev "${p}::${rev}")
                endif()
            endforeach()
            if(NOT "${filens}" STREQUAL "")
                set(rev "${filens}::${rev}")
            endif()
            set(base "")
            if(bases MATCHES ": *(public |private |protected |)([A-Za-z0-9_:]+)")
                string(REGEX REPLACE ".*::" "" base "${CMAKE_MATCH_2}")
            endif()
            set_property(GLOBAL PROPERTY SDEF_${sname}_BASE "${base}")
            set(ownbody "${body}")
            while(ownbody MATCHES "\\{[^{}]*\\}")
                string(REGEX REPLACE "\\{[^{}]*\\}" "" ownbody "${ownbody}")
            endwhile()

            set(ctorable 1)
            set(_ob " ${ownbody}")
            if(_ob MATCHES "[^~A-Za-z0-9_]${sname} *\\(" AND NOT _ob MATCHES "[^~A-Za-z0-9_]${sname} *\\( *\\)")
                set(ctorable 0)
            endif()
            if(ctorable AND NOT "${base}" STREQUAL "")
                get_property(_bc GLOBAL PROPERTY SDEF_${base}_CTOR)
                if("${_bc}" STREQUAL "0")
                    set(ctorable 0)
                endif()
            endif()
            set_property(GLOBAL PROPERTY SDEF_${sname}_CTOR "${ctorable}")
            set_property(GLOBAL APPEND PROPERTY CPPDEFS "${sname}=${rev}")
            set_property(GLOBAL PROPERTY CPPQ_${sname} "${rev}")

            _ctor_args("${_ob}" "${sname}" "${rev}" _ca)
            set_property(GLOBAL PROPERTY SDEF_${sname}_CTORARGS "${_ca}")

            _struct_own_fields("${ownbody}" "${sc}" fields "${chain}")
            set_property(GLOBAL PROPERTY SDEF_${sname}_FIELDS "${fields}")
        endif()

        math(EXPR after "${endpos}+1")
        string(SUBSTRING "${flat}" ${after} -1 flat)
    endwhile()
endfunction()

function(_struct_all_fields name out)
    get_property(base GLOBAL PROPERTY SDEF_${name}_BASE)
    get_property(own GLOBAL PROPERTY SDEF_${name}_FIELDS)
    set(pre "")
    if(NOT "${base}" STREQUAL "")
        get_property(bseen GLOBAL PROPERTY SDEF_SEEN_${base})
        if(NOT "${bseen}" STREQUAL "")
            _struct_all_fields("${base}" pre)
        endif()
    endif()
    string(STRIP "${pre} ${own}" all)
    set(${out} "${all}" PARENT_SCOPE)
endfunction()

function(_struct_all_fieldcpp name out)
    get_property(base GLOBAL PROPERTY SDEF_${name}_BASE)
    get_property(own GLOBAL PROPERTY SDEF_${name}_FIELDCPP)
    set(pre "")
    if(NOT "${base}" STREQUAL "")
        get_property(bseen GLOBAL PROPERTY SDEF_SEEN_${base})
        if(NOT "${bseen}" STREQUAL "")
            _struct_all_fieldcpp("${base}" pre)
        endif()
    endif()
    set(all ${pre} ${own})
    set(${out} "${all}" PARENT_SCOPE)
endfunction()

function(_struct_all_members name out)
    get_property(base GLOBAL PROPERTY SDEF_${name}_BASE)
    get_property(own GLOBAL PROPERTY SDEF_${name}_MEMBERS)
    set(pre "")
    if(NOT "${base}" STREQUAL "")
        get_property(bseen GLOBAL PROPERTY SDEF_SEEN_${base})
        if(NOT "${bseen}" STREQUAL "")
            _struct_all_members("${base}" pre)
        endif()
    endif()
    set(all ${pre} ${own})
    set(${out} "${all}" PARENT_SCOPE)
endfunction()

function(_emit_member sname snake camel cpptype tt_hint tokens_var map_var flagbit_var)
    string(REGEX REPLACE "^const +" "" cpptype "${cpptype}")
    string(REGEX REPLACE " *&$" "" cpptype "${cpptype}")
    string(STRIP "${cpptype}" cpptype)
    set(opt 0)
    if(cpptype MATCHES "^std::optional<(.+)>$")
        set(opt 1)
        set(cpptype "${CMAKE_MATCH_1}")
    endif()
    if(NOT "${tt_hint}" STREQUAL "")
        set(tt "${tt_hint}")
    else()
        _cpp_to_tl("${cpptype}" tt)
    endif()

    set(${flagbit_var} "${${flagbit_var}}")
    if(opt)
        set(_bit "${${flagbit_var}}")
        list(APPEND ${tokens_var} "${snake}:flags.${_bit}?${tt}")
        math(EXPR _bit "${_bit}+1")
        set(${flagbit_var} "${_bit}" PARENT_SCOPE)
    else()
        list(APPEND ${tokens_var} "${snake}:${tt}")
    endif()
    list(APPEND ${map_var} "${sname}.${snake}=${camel}")
    set(${tokens_var} "${${tokens_var}}" PARENT_SCOPE)
    set(${map_var} "${${map_var}}" PARENT_SCOPE)
endfunction()

function(_gen_structs headers out)
    string(ASCII 1 SC)
    foreach(h ${headers})
        if(NOT EXISTS "${h}")
            continue()
        endif()
        file(READ "${h}" src)
        string(REGEX REPLACE "//[^\n]*" "" src "${src}")
        string(REGEX REPLACE "/\\*[^*]*\\*+([^/*][^*]*\\*+)*/" "" src "${src}")
        string(REGEX REPLACE "= *\\{[^{}]*\\}" "" src "${src}")
        string(REGEX REPLACE "[ \t\r\n]+" " " flat "${src}")
        string(REGEX REPLACE "enum( +class)? +[A-Za-z0-9_]+ *\\{[^{}]*\\}" "" flat "${flat}")
        set(filens "")
        if(flat MATCHES "namespace +([A-Za-z0-9_:]+)")
            set(filens "${CMAKE_MATCH_1}")
        endif()
        string(REPLACE ";" "${SC}" flat "${flat}")
        _scan_structs("${flat}" "${SC}" "" "${filens}")
    endforeach()

    set(res "")
    string(ASCII 2 SC2)
    get_property(names GLOBAL PROPERTY SDEF_NAMES)
    foreach(sname ${names})
        _struct_all_fields("${sname}" fields)
        if(fields STREQUAL "")
            continue()
        endif()
        _nsify("${sname}" tpn)
        _camel_first("${sname}" ctor)

        set(tokens "")
        set(cmap "")
        set(flagbit 0)
        get_property(_ca GLOBAL PROPERTY SDEF_${sname}_CTORARGS)
        if(NOT "${_ca}" STREQUAL "")
            _split_top("${_ca}" "," _cas)
            foreach(_a ${_cas})
                if(NOT _a MATCHES "^([A-Za-z0-9_]+)\\|(.+)$")
                    continue()
                endif()
                set(_camel "${CMAKE_MATCH_1}")
                set(_ct "${CMAKE_MATCH_2}")
                _emit_member("${sname}" "${_camel}" "${_camel}" "${_ct}" "" tokens cmap flagbit)
            endforeach()
        else()
            _struct_all_members("${sname}" _mems)
            foreach(_m ${_mems})
                string(REPLACE "${SC2}" ";" _mp "${_m}")
                list(GET _mp 0 _sn)
                list(GET _mp 1 _tt)
                list(GET _mp 2 _camel)
                list(GET _mp 3 _raw)
                _emit_member("${sname}" "${_sn}" "${_camel}" "${_raw}" "${_tt}" tokens cmap flagbit)
            endforeach()
        endif()

        set(fstr "")
        set(_flagsdone 0)
        foreach(_tok ${tokens})
            if(_tok MATCHES ":flags\\.[0-9]+\\?" AND NOT _flagsdone)
                string(APPEND fstr " flags:#")
                set(_flagsdone 1)
            endif()
            string(APPEND fstr " ${_tok}")
        endforeach()
        string(STRIP "${fstr}" fstr)

        get_property(_ctorable GLOBAL PROPERTY SDEF_${sname}_CTOR)
        if(_ctorable)
            string(APPEND res "empty${sname} = ${tpn};\n")
        endif()
        string(APPEND res "${ctor} ${fstr} = ${tpn};\n")

        foreach(_e ${cmap})
            set_property(GLOBAL APPEND PROPERTY CPPDEFS "${_e}")
        endforeach()
    endforeach()
    set(${out} "${res}" PARENT_SCOPE)
endfunction()

function(_referenced tn text out)
    string(REGEX MATCH "[^A-Za-z0-9_]${tn}[^A-Za-z0-9_]" hit " ${text} ")
    if(hit STREQUAL "")
        set(${out} FALSE PARENT_SCOPE)
    else()
        set(${out} TRUE PARENT_SCOPE)
    endif()
endfunction()

function(_err_pad code out)
    set(k "${code}")
    string(LENGTH "${k}" kl)
    while(kl LESS 5)
        set(k "0${k}")
        string(LENGTH "${k}" kl)
    endwhile()
    set(${out} "${k}" PARENT_SCOPE)
endfunction()

function(_gen_errors headers out)
    string(ASCII 1 SC)
    set(pairs "")
    set(catcount 0)
    foreach(h ${headers})
        if(NOT EXISTS "${h}")
            continue()
        endif()
        file(READ "${h}" src)
        string(REGEX REPLACE "//[^\n]*" "" src "${src}")
        string(REGEX REPLACE "\\\\[ \t]*\n" " " src "${src}")
        string(REGEX REPLACE "#[^\n]*" "" src "${src}")
        string(REGEX REPLACE "[ \t\r\n]+" " " flat "${src}")
        set(fns "")
        if(flat MATCHES "namespace +([A-Za-z0-9_:]+)")
            set(fns "${CMAKE_MATCH_1}")
        endif()
        string(REGEX MATCHALL "EX_GROUP(_INTERNAL|_EXPORT)? *\\( *[A-Za-z0-9_]+ *\\)|EX_DECLARE(_INTERNAL)? *\\( *[A-Za-z0-9_]+ *, *[A-Za-z0-9_:]+ *\\)" toks "${flat}")
        foreach(tok ${toks})
            if(tok MATCHES "^EX_GROUP(_INTERNAL|_EXPORT)? *\\( *([A-Za-z0-9_]+)")
                set(gkind "${CMAKE_MATCH_1}")
                set(gname "${CMAKE_MATCH_2}")
                math(EXPR catcount "${catcount}+1")
                math(EXPR catbase "${catcount}*100")
                set_property(GLOBAL PROPERTY ERRCAT_${gname} "${catbase}")
                set_property(GLOBAL PROPERTY ERROFF_${gname} "0")
                if("${gkind}" STREQUAL "_EXPORT")
                    _camel_first("${gname}" cc)
                    _err_pad("${catbase}" key)
                    list(APPEND pairs "${key}${SC}${cc} = Error<-${catbase}>")
                    set_property(GLOBAL APPEND PROPERTY CPPDEFS "${cc}=${fns}::${gname}")
                endif()
                if(NOT "${gkind}" STREQUAL "_INTERNAL")
                    string(REGEX REPLACE "Exception$" "" _eb "${gname}")
                    set_property(GLOBAL APPEND PROPERTY CPPDEFS "${_eb}#exc=|${fns}::${gname}")
                endif()
            elseif(tok MATCHES "^EX_DECLARE(_INTERNAL)? *\\( *([A-Za-z0-9_]+) *, *([A-Za-z0-9_:]+)")
                set(internal "${CMAKE_MATCH_1}")
                set(ename "${CMAKE_MATCH_2}")
                set(base "${CMAKE_MATCH_3}")
                if(NOT "${internal}" STREQUAL "")
                    continue()
                endif()
                string(REGEX REPLACE "^.*::" "" gbase "${base}")
                get_property(cb GLOBAL PROPERTY ERRCAT_${gbase})
                if("${cb}" STREQUAL "")
                    message(FATAL_ERROR "GenTl: error '${ename}' base group '${gbase}' not declared before it")
                endif()
                get_property(off GLOBAL PROPERTY ERROFF_${gbase})
                math(EXPR off "${off}+1")
                set_property(GLOBAL PROPERTY ERROFF_${gbase} "${off}")
                math(EXPR code "${cb}+${off}")
                _camel_first("${ename}" cc)
                _err_pad("${code}" key)
                list(APPEND pairs "${key}${SC}${cc} = Error<-${code}>")
                set_property(GLOBAL APPEND PROPERTY CPPDEFS "${cc}=${fns}::${ename}")
                string(REGEX REPLACE "Exception$" "" _eb "${ename}")
                string(REGEX REPLACE "Exception$" "" _pb "${gbase}")
                set_property(GLOBAL APPEND PROPERTY CPPDEFS "${_eb}#exc=${_pb}|${fns}::${ename}")
            endif()
        endforeach()
    endforeach()

    list(SORT pairs)
    set(res "")
    set(prevbucket "")
    foreach(p ${pairs})
        string(FIND "${p}" "${SC}" s)
        string(SUBSTRING "${p}" 0 ${s} key)
        math(EXPR r "${s}+1")
        string(SUBSTRING "${p}" ${r} -1 line)
        string(REGEX REPLACE "^0+" "" nk "${key}")
        math(EXPR bucket "${nk}/100")
        if(NOT "${prevbucket}" STREQUAL "" AND NOT "${bucket}" STREQUAL "${prevbucket}")
            string(APPEND res "\n")
        endif()
        string(APPEND res "${line};\n")
        set(prevbucket "${bucket}")
    endforeach()
    set(${out} "${res}" PARENT_SCOPE)
endfunction()

function(_pascal1 in out)
    string(SUBSTRING "${in}" 0 1 h)
    string(TOUPPER "${h}" h)
    string(SUBSTRING "${in}" 1 -1 t)
    set(${out} "${h}${t}" PARENT_SCOPE)
endfunction()

function(_v2_build_maps)
    get_property(cppdefs GLOBAL PROPERTY CPPDEFS)
    foreach(d ${cppdefs})
        if(d MATCHES "^([A-Za-z0-9_]+)#exc=([A-Za-z0-9_]*)\\|(.+)$")
            set_property(GLOBAL PROPERTY V2_EXCPAR_${CMAKE_MATCH_1} "${CMAKE_MATCH_2}")
            set_property(GLOBAL PROPERTY V2_EXCCPP_${CMAKE_MATCH_1} "${CMAKE_MATCH_3}")
            set_property(GLOBAL APPEND PROPERTY V2_EXCKEYS "${CMAKE_MATCH_1}")
        elseif(d MATCHES "^([A-Za-z0-9_]+)\\.([A-Za-z0-9_]+)=([A-Za-z0-9_]+)(\\|(.+))?$")
            set_property(GLOBAL PROPERTY V2_MEMB_${CMAKE_MATCH_1}_${CMAKE_MATCH_2} "${CMAKE_MATCH_3}")
            if(NOT "${CMAKE_MATCH_5}" STREQUAL "")
                set_property(GLOBAL PROPERTY V2_SPEC_${CMAKE_MATCH_1}_${CMAKE_MATCH_2} "${CMAKE_MATCH_5}")
            endif()
        elseif(d MATCHES "^([A-Za-z0-9_]+)=([A-Za-z0-9_:]+)$")
            set_property(GLOBAL PROPERTY V2_PATH_${CMAKE_MATCH_1} "${CMAKE_MATCH_2}")
        endif()
    endforeach()
endfunction()

function(_map_lines text fnname out)
    set(res "")
    while(NOT "${text}" STREQUAL "")
        string(FIND "${text}" "\n" nl)
        if(nl LESS 0)
            set(line "${text}")
            set(text "")
        else()
            string(SUBSTRING "${text}" 0 ${nl} line)
            math(EXPR a "${nl}+1")
            string(SUBSTRING "${text}" ${a} -1 text)
        endif()
        if("${line}" STREQUAL "")
            string(APPEND res "\n")
        else()
            cmake_language(CALL "${fnname}" "${line}" _ol)
            string(APPEND res "${_ol}\n")
        endif()
    endwhile()
    set(${out} "${res}" PARENT_SCOPE)
endfunction()

function(_v2_field_names fieldstr out)
    set(names "")
    string(REPLACE " " ";" toks "${fieldstr}")
    foreach(t ${toks})
        if(t STREQUAL "flags:#")
            continue()
        endif()
        if(t MATCHES "^([a-zA-Z0-9_]+):")
            list(APPEND names "${CMAKE_MATCH_1}")
        endif()
    endforeach()
    set(${out} "${names}" PARENT_SCOPE)
endfunction()

function(_v2_comment owner fieldstr declcpp out)
    set(c "//")
    if(NOT "${declcpp}" STREQUAL "")
        string(APPEND c " @${declcpp}")
    endif()
    _v2_field_names("${fieldstr}" fns)
    foreach(f ${fns})
        get_property(mc GLOBAL PROPERTY V2_MEMB_${owner}_${f})
        get_property(sp GLOBAL PROPERTY V2_SPEC_${owner}_${f})
        set(defcamel "${f}")
        set(tok "${f}")
        set(need 0)
        if(NOT "${mc}" STREQUAL "" AND NOT "${mc}" STREQUAL "${defcamel}")
            set(tok "${tok}=${mc}")
            set(need 1)
        endif()
        if(NOT "${sp}" STREQUAL "")
            set(tok "${tok}|${sp}")
            set(need 1)
        endif()
        if(need)
            string(APPEND c " ${tok}")
        endif()
    endforeach()
    set(${out} "${c}" PARENT_SCOPE)
endfunction()

function(_xf_type line out)
    if(NOT line MATCHES "^([A-Za-z0-9_]+)( .*)? = (([A-Za-z0-9_]+)\\.)?([A-Za-z0-9_]+);?$")
        set(${out} "${line}" PARENT_SCOPE)
        return()
    endif()
    string(STRIP "${CMAKE_MATCH_2}" fieldstr)
    set(bare "${CMAKE_MATCH_5}")
    if("${fieldstr}" STREQUAL "")
        _with_id("${line}" r)
        set(${out} "${r}" PARENT_SCOPE)
        return()
    endif()
    get_property(cpp GLOBAL PROPERTY V2_PATH_${bare})
    _v2_comment("${bare}" "${fieldstr}" "${cpp}" cm)
    _with_id("${line} ${cm}" r)
    set(${out} "${r}" PARENT_SCOPE)
endfunction()

function(_xf_cb line out)
    if(NOT line MATCHES "^([A-Za-z0-9_]+)( .*)? = ([A-Za-z0-9_]+);?$")
        set(${out} "${line}" PARENT_SCOPE)
        return()
    endif()
    string(STRIP "${CMAKE_MATCH_2}" fieldstr)
    set(cbtype "${CMAKE_MATCH_3}")
    _v2_comment("${cbtype}" "${fieldstr}" "" cm)
    if(cm STREQUAL "//")
        _with_id("${line}" r)
    else()
        _with_id("${line} ${cm}" r)
    endif()
    set(${out} "${r}" PARENT_SCOPE)
endfunction()

function(_xf_fn line out)
    _with_id("${line}" r)
    set(${out} "${r}" PARENT_SCOPE)
endfunction()

function(_v2_enums raw out)
    set(res "")
    set(curtype "")
    while(NOT "${raw}" STREQUAL "")
        string(FIND "${raw}" "\n" nl)
        if(nl LESS 0)
            set(line "${raw}")
            set(raw "")
        else()
            string(SUBSTRING "${raw}" 0 ${nl} line)
            math(EXPR a "${nl}+1")
            string(SUBSTRING "${raw}" ${a} -1 raw)
        endif()
        if("${line}" STREQUAL "")
            continue()
        endif()
        if(NOT line MATCHES "^([A-Za-z0-9_]+) = Enum<(([A-Za-z0-9_]+)\\.)?([A-Za-z0-9_]+), (-?[0-9]+)>;?$")
            continue()
        endif()
        set(mem "${CMAKE_MATCH_1}")
        set(ns "${CMAKE_MATCH_3}")
        set(type "${CMAKE_MATCH_4}")
        if(ns STREQUAL "")
            set(tlType "${type}")
        else()
            set(tlType "${ns}.${type}")
        endif()
        if(NOT "${type}" STREQUAL "${curtype}")
            get_property(cpp GLOBAL PROPERTY V2_PATH_${type})
            string(APPEND res "\n// enum ${tlType} @${cpp}\n")
            set(curtype "${type}")
        endif()
        _camel_first("${type}" lt)
        _pascal1("${mem}" mp)
        if(ns STREQUAL "")
            set(ctor "${lt}${mp}")
        else()
            set(ctor "${ns}.${lt}${mp}")
        endif()
        get_property(enumcpp GLOBAL PROPERTY V2_MEMB_${type}_${mem})
        _pascal1("${mem}" derived)
        set(raw2 "${ctor} = ${tlType};")
        if(NOT "${enumcpp}" STREQUAL "" AND NOT "${enumcpp}" STREQUAL "${derived}")
            set(raw2 "${raw2} // @${enumcpp}")
        endif()
        _with_id("${raw2}" idline)
        string(APPEND res "${idline}\n")
    endwhile()
    set(${out} "${res}" PARENT_SCOPE)
endfunction()

function(_v2_errors out)
    get_property(keys GLOBAL PROPERTY V2_EXCKEYS)
    set(res "")
    foreach(k ${keys})
        get_property(par GLOBAL PROPERTY V2_EXCPAR_${k})
        if(NOT "${par}" STREQUAL "")
            continue()
        endif()
        get_property(cpp GLOBAL PROPERTY V2_EXCCPP_${k})
        string(REGEX REPLACE "^.*::" "" gcls "${cpp}")
        set_property(GLOBAL PROPERTY V2_GRPCLS_${k} "${gcls}")
        _camel_first("${gcls}" gctor)
        _with_id("${gctor} = Error<${gcls}>; // @${cpp}" idline)
        string(APPEND res "${idline}\n")
    endforeach()
    string(APPEND res "\n")
    foreach(k ${keys})
        get_property(par GLOBAL PROPERTY V2_EXCPAR_${k})
        if("${par}" STREQUAL "")
            continue()
        endif()
        get_property(cpp GLOBAL PROPERTY V2_EXCCPP_${k})
        get_property(pcls GLOBAL PROPERTY V2_GRPCLS_${par})
        string(REGEX REPLACE "^.*::" "" lcls "${cpp}")
        _camel_first("${lcls}" lctor)
        _with_id("${lctor} = ${pcls}; // @${cpp}" idline)
        string(APPEND res "${idline}\n")
    endforeach()
    set(${out} "${res}" PARENT_SCOPE)
endfunction()

function(gen_ntl hpp cpp alias_map struct_headers exc_headers out_tl)
    _gentl_load_aliases("${alias_map}")
    _gentl_scan_ns("${struct_headers}")
    _gentl_scan_cbargs("${cpp}")
    _gen_functions("${hpp}" fns cbs)
    _gen_enums("${struct_headers}" enums_all)
    _gen_structs("${struct_headers}" structs_all)
    _gen_errors("${exc_headers}" errs)

    string(ASCII 1 SC)
    set(refs "${fns}${cbs}")

    string(REPLACE ";" "${SC}" sp "${structs_all}")
    string(REPLACE "\n" ";" slines "${sp}")
    set(struct_pairs "")
    set(changed TRUE)
    while(changed)
        set(changed FALSE)
        set(next "")
        foreach(ln ${slines})
            string(REPLACE "${SC}" ";" line "${ln}")
            if(line MATCHES "= ([A-Za-z0-9_]+)\\.([A-Za-z0-9_]+);$")
                set(tn "${CMAKE_MATCH_2}")
                set(ns "${CMAKE_MATCH_1}")
            elseif(line MATCHES "= ([A-Za-z0-9_]+);$")
                set(tn "${CMAKE_MATCH_1}")
                set(ns "_root")
            else()
                continue()
            endif()
            _referenced("${tn}" "${refs}" hit)
            if(hit)
                list(APPEND struct_pairs "${ns}|${ln}")
                string(APPEND refs " ${line}")
            else()
                list(APPEND next "${ln}")
            endif()
        endforeach()
        if(NOT "${next}" STREQUAL "${slines}")
            set(changed TRUE)
        endif()
        set(slines "${next}")
    endwhile()

    list(SORT struct_pairs)
    set(emitted_structs "")
    set(prevns "")
    foreach(p ${struct_pairs})
        string(FIND "${p}" "|" bar)
        string(SUBSTRING "${p}" 0 ${bar} ns)
        math(EXPR r "${bar}+1")
        string(SUBSTRING "${p}" ${r} -1 ln)
        string(REPLACE "${SC}" ";" line "${ln}")
        if(NOT "${prevns}" STREQUAL "" AND NOT "${ns}" STREQUAL "${prevns}")
            string(APPEND emitted_structs "\n")
        endif()
        string(APPEND emitted_structs "${line}\n")
        set(prevns "${ns}")
    endforeach()

    string(REPLACE ";" "${SC}" ep "${enums_all}")
    string(REPLACE "\n" ";" elines "${ep}")
    set(emitted_enums "")
    set(prevtype "")
    foreach(ln ${elines})
        string(REPLACE "${SC}" ";" line "${ln}")
        if(line MATCHES "Enum<(([A-Za-z0-9_]+\\.)?[A-Za-z0-9_]+),")
            set(fulltype "${CMAKE_MATCH_1}")
        else()
            continue()
        endif()
        string(REGEX REPLACE "^.*\\." "" tn "${fulltype}")
        _referenced("${tn}" "${refs}" hit)
        if(hit)
            if(NOT "${prevtype}" STREQUAL "" AND NOT "${fulltype}" STREQUAL "${prevtype}")
                string(APPEND emitted_enums "\n")
            endif()
            string(APPEND emitted_enums "${line}\n")
            set(prevtype "${fulltype}")
        endif()
    endforeach()

    _v2_build_maps()
    _v2_errors(errs_v2)
    _v2_enums("${emitted_enums}" enums_v2)
    _map_lines("${emitted_structs}" _xf_type structs_v2)
    _map_lines("${cbs}" _xf_cb cbs_v2)
    _map_lines("${fns}" _xf_fn fns_v2)

    file(WRITE "${out_tl}" "// @generated from ntgcalls.hpp -- DO NOT EDIT\n\n---errors---\n${errs_v2}\n---enums---\n${enums_v2}\n---types---\n${structs_v2}\n---callbacks---\n${cbs_v2}\n---functions---\n${fns_v2}")
endfunction()
