function(_cpp_class name out)
    set(${out} "ntgcalls::${name}" PARENT_SCOPE)
endfunction()

function(_snake in out)
    string(REGEX REPLACE "([a-z])([A-Z])" "\\1_\\2" s "${in}")
    string(REGEX REPLACE "([A-Z][A-Z]+)([A-Z][a-z])" "\\1_\\2" s "${s}")
    string(REGEX REPLACE "([0-9])([A-Z][a-z])" "\\1_\\2" s "${s}")
    string(TOLOWER "${s}" s)
    set(${out} "${s}" PARENT_SCOPE)
endfunction()

function(_enum_disp cpp out)
    if(cpp MATCHES "^k([A-Z].*)$")
        set(c "${CMAKE_MATCH_1}")
    else()
        set(c "${cpp}")
    endif()
    _snake("${c}" c)
    string(TOUPPER "${c}" c)
    set(${out} "${c}" PARENT_SCOPE)
endfunction()

function(_ntl_scalar_cpp tl out)
    if(tl STREQUAL "int8")
        set(r "int8_t")
    elseif(tl STREQUAL "uint8")
        set(r "uint8_t")
    elseif(tl STREQUAL "int16")
        set(r "int16_t")
    elseif(tl STREQUAL "uint16")
        set(r "uint16_t")
    elseif(tl STREQUAL "int")
        set(r "int32_t")
    elseif(tl STREQUAL "uint")
        set(r "uint32_t")
    elseif(tl STREQUAL "long")
        set(r "int64_t")
    elseif(tl STREQUAL "ulong")
        set(r "uint64_t")
    elseif(tl STREQUAL "bool")
        set(r "bool")
    elseif(tl STREQUAL "double")
        set(r "double")
    elseif(tl STREQUAL "string")
        set(r "std::string")
    else()
        set(r "")
    endif()
    set(${out} "${r}" PARENT_SCOPE)
endfunction()

function(_ntl_cpp tl out)
    string(STRIP "${tl}" tl)
    if(tl MATCHES "^Vector<(.+)>$")
        _ntl_cpp("${CMAKE_MATCH_1}" _in)
        set(${out} "std::vector<${_in}>" PARENT_SCOPE)
        return()
    endif()
    if(tl STREQUAL "bytes")
        set(${out} "bytes::binary" PARENT_SCOPE)
        return()
    endif()
    _ntl_scalar_cpp("${tl}" _sc)
    if(NOT "${_sc}" STREQUAL "")
        set(${out} "${_sc}" PARENT_SCOPE)
        return()
    endif()
    if(tl MATCHES "^[a-z][a-z0-9_]*\\.([A-Za-z0-9_]+)$")
        set(_bare "${CMAKE_MATCH_1}")
    else()
        set(_bare "${tl}")
    endif()
    get_property(_ct GLOBAL PROPERTY CPPTYPE_${_bare})
    if(NOT "${_ct}" STREQUAL "")
        set(${out} "${_ct}" PARENT_SCOPE)
    else()
        string(REPLACE "." "::" _c "${tl}")
        set(${out} "${_c}" PARENT_SCOPE)
    endif()
endfunction()

function(_cpp_arg ft fopt out_cpp out_byval)
    _ntl_cpp("${ft}" _c)
    set(_bv "")
    if(fopt)
        set(_c "std::optional<${_c}>")
    elseif(ft MATCHES "^(int8|uint8|int16|uint16|int|uint|long|ulong|bool|double)$")
        set(_bv "1")
    elseif(ft MATCHES "^(([a-z][a-z0-9_]*)\\.)?([A-Za-z0-9_]+)$")
        get_property(_ei GLOBAL PROPERTY ENUMIDX_${CMAKE_MATCH_3})
        if(NOT "${_ei}" STREQUAL "")
            set(_bv "1")
        endif()
    endif()
    set(${out_cpp} "${_c}" PARENT_SCOPE)
    set(${out_byval} "${_bv}" PARENT_SCOPE)
endfunction()

function(_enrich_arg ap ft fopt)
    if(ft STREQUAL "bytes")
        set_property(GLOBAL PROPERTY ${ap}.bytes "1")
        set_property(GLOBAL PROPERTY ${ap}.bytetype "bytes::binary")
        set_property(GLOBAL PROPERTY ${ap}.wrap "1")
    endif()
    _cpp_arg("${ft}" "${fopt}" _bc _bv)
    if(_bv)
        set_property(GLOBAL PROPERTY ${ap}.byval "1")
    endif()
    set_property(GLOBAL PROPERTY ${ap}.cpptype "${_bc}")
endfunction()

function(_parse_fields args pfx coll)
    if("${args}" STREQUAL "")
        return()
    endif()
    string(REPLACE " " ";" al "${args}")
    set(idx 0)
    foreach(a ${al})
        if(a STREQUAL "flags:#")
            continue()
        endif()
        if(a MATCHES "^([a-zA-Z0-9_]+):(.+)$")
            set(_fnm "${CMAKE_MATCH_1}")
            set(_fty "${CMAKE_MATCH_2}")
            set(_fopt "")
            if(_fty MATCHES "^flags\\.[0-9]+\\?(.+)$")
                set(_fty "${CMAKE_MATCH_1}")
                set(_fopt "1")
            endif()
            set(pp "${pfx}.${coll}.${idx}")
            set_property(GLOBAL APPEND PROPERTY ${pfx}.${coll} "${pp}")
            set_property(GLOBAL PROPERTY ${pp}.name "${_fnm}")
            set_property(GLOBAL PROPERTY ${pp}.type "${_fty}")
            if(_fopt)
                set_property(GLOBAL PROPERTY ${pp}.optional "1")
            endif()
            math(EXPR idx "${idx}+1")
        endif()
    endforeach()
    get_property(_items GLOBAL PROPERTY ${pfx}.${coll})
    list(LENGTH _items _n)
    math(EXPR _last "${_n}-1")
    set(_i 0)
    foreach(_it ${_items})
        if(_i EQUAL _last)
            set_property(GLOBAL PROPERTY ${_it}.sep "")
        else()
            set_property(GLOBAL PROPERTY ${_it}.sep ",")
        endif()
        math(EXPR _i "${_i}+1")
    endforeach()
endfunction()

function(_struct_ensure stype sns out)
    get_property(si GLOBAL PROPERTY STRUCTIDX_${stype})
    if("${si}" STREQUAL "")
        get_property(slist GLOBAL PROPERTY structs)
        list(LENGTH slist si)
        set_property(GLOBAL APPEND PROPERTY structs "structs.${si}")
        set_property(GLOBAL PROPERTY STRUCTIDX_${stype} "${si}")
        set_property(GLOBAL PROPERTY structs.${si}.name "${stype}")
        set_property(GLOBAL PROPERTY structs.${si}.ns "${sns}")
    endif()
    set(${out} "${si}" PARENT_SCOPE)
endfunction()

function(ntl_parse tl_file)
    file(READ "${tl_file}" content)
    string(REPLACE "\r" "" content "${content}")

    set(section "")
    while(NOT "${content}" STREQUAL "")
        string(FIND "${content}" "\n" _nl)
        if(_nl LESS 0)
            set(line "${content}")
            set(content "")
        else()
            string(SUBSTRING "${content}" 0 ${_nl} line)
            math(EXPR _a "${_nl}+1")
            string(SUBSTRING "${content}" ${_a} -1 content)
        endif()
        string(STRIP "${line}" line)
        if(line STREQUAL "")
            continue()
        endif()
        if(line STREQUAL "---errors---")
            set(section "errors")
            continue()
        elseif(line STREQUAL "---enums---")
            set(section "enums")
            continue()
        elseif(line STREQUAL "---types---")
            set(section "structs")
            continue()
        elseif(line STREQUAL "---callbacks---")
            set(section "callbacks")
            continue()
        elseif(line STREQUAL "---functions---")
            set(section "functions")
            continue()
        endif()

        if(section STREQUAL "enums" AND line MATCHES "^// enum (([A-Za-z0-9_]+)\\.)?([A-Za-z0-9_]+) @(.+)$")
            set(_ens "${CMAKE_MATCH_2}")
            set(_etype "${CMAKE_MATCH_3}")
            string(STRIP "${CMAKE_MATCH_4}" _ecpp)
            set_property(GLOBAL PROPERTY CPPTYPE_${_etype} "${_ecpp}")
            get_property(ei GLOBAL PROPERTY ENUMIDX_${_etype})
            if("${ei}" STREQUAL "")
                get_property(elist GLOBAL PROPERTY enums)
                list(LENGTH elist ei)
                set_property(GLOBAL APPEND PROPERTY enums "enums.${ei}")
                set_property(GLOBAL PROPERTY ENUMIDX_${_etype} "${ei}")
                set_property(GLOBAL PROPERTY enums.${ei}.name "${_etype}")
                set_property(GLOBAL PROPERTY enums.${ei}.ns "${_ens}")
                set_property(GLOBAL PROPERTY enums.${ei}.cpp "${_ecpp}")
                set_property(GLOBAL PROPERTY enums.${ei}.emit "1")
                set_property(GLOBAL PROPERTY ECOUNT_${ei} "0")
            endif()
            continue()
        endif()
        if(line MATCHES "^//")
            continue()
        endif()

        set(comment "")
        if(line MATCHES "^(.*[^ ]) +// @(.+)$")
            set(line "${CMAKE_MATCH_1}")
            string(STRIP "${CMAKE_MATCH_2}" comment)
        endif()
        string(REGEX REPLACE ";[ \t]*$" "" line "${line}")
        string(REGEX REPLACE "#[0-9a-f]+" "" line "${line}")
        string(STRIP "${line}" line)

        if(section STREQUAL "errors")
            if(comment STREQUAL "" OR NOT line MATCHES "^([A-Za-z0-9_]+) = (.+)$")
                continue()
            endif()
            set(_ename "${CMAKE_MATCH_1}")
            set(_erhs "${CMAKE_MATCH_2}")
            get_property(erlist GLOBAL PROPERTY errors)
            list(LENGTH erlist ii)
            set(pfx "errors.${ii}")
            set_property(GLOBAL APPEND PROPERTY errors "${pfx}")
            set_property(GLOBAL PROPERTY ${pfx}.name "${_ename}")
            set_property(GLOBAL PROPERTY ${pfx}.cpp "${comment}")
            set_property(GLOBAL PROPERTY CPPTYPE_${_ename} "${comment}")

            string(REGEX REPLACE "^.*::" "" _ecls "${comment}")
            string(REGEX REPLACE "Exception$" "" _ecls "${_ecls}")
            set(_eparent "")
            if(NOT _erhs MATCHES "^Error<")
                string(REGEX REPLACE "Exception$" "" _eparent "${_erhs}")
            endif()
            get_property(_xl GLOBAL PROPERTY excs)
            list(LENGTH _xl _xi)
            set(_xpfx "excs.${_xi}")
            set_property(GLOBAL APPEND PROPERTY excs "${_xpfx}")
            set_property(GLOBAL PROPERTY ${_xpfx}.name "${_ecls}")
            set_property(GLOBAL PROPERTY ${_xpfx}.parent "${_eparent}")
            set_property(GLOBAL PROPERTY ${_xpfx}.cpp "${comment}")

        elseif(section STREQUAL "enums")
            if(NOT line MATCHES "^(([a-z][a-z0-9_]*)\\.)?([A-Za-z0-9_]+) = (([a-z][a-z0-9_]*)\\.)?([A-Za-z0-9_]+)$")
                continue()
            endif()
            set(_ctor "${CMAKE_MATCH_3}")
            set(_etype "${CMAKE_MATCH_6}")
            get_property(ei GLOBAL PROPERTY ENUMIDX_${_etype})
            if("${ei}" STREQUAL "")
                continue()
            endif()
            string(LENGTH "${_etype}" _tlen)
            string(SUBSTRING "${_ctor}" ${_tlen} -1 _memderived)
            if(NOT "${comment}" STREQUAL "")
                set(_memcpp "${comment}")
            else()
                set(_memcpp "${_memderived}")
            endif()
            get_property(mi GLOBAL PROPERTY ECOUNT_${ei})
            set(pfx "enums.${ei}.members.${mi}")
            set_property(GLOBAL APPEND PROPERTY enums.${ei}.members "${pfx}")
            set_property(GLOBAL PROPERTY ${pfx}.cpp "${_memcpp}")
            set_property(GLOBAL PROPERTY ${pfx}.ord "${mi}")
            _enum_disp("${_memcpp}" _disp)
            set_property(GLOBAL PROPERTY ${pfx}.disp "${_disp}")
            math(EXPR mi "${mi}+1")
            set_property(GLOBAL PROPERTY ECOUNT_${ei} "${mi}")

        elseif(section STREQUAL "structs")
            if(NOT line MATCHES "^([A-Za-z0-9_]+)( .*)? = (([a-z][a-z0-9_]*)\\.)?([A-Za-z0-9_]+)$")
                continue()
            endif()
            set(_ctor "${CMAKE_MATCH_1}")
            string(STRIP "${CMAKE_MATCH_2}" _sfields)
            set(_sns "${CMAKE_MATCH_4}")
            set(_stype "${CMAKE_MATCH_5}")
            _struct_ensure("${_stype}" "${_sns}" si)
            if(_ctor MATCHES "^empty[A-Z]" AND "${_sfields}" STREQUAL "")
                set_property(GLOBAL PROPERTY structs.${si}.ctorable "1")
                continue()
            endif()
            if(NOT "${comment}" STREQUAL "")
                string(REGEX REPLACE " +" ";" _ctoks "${comment}")
                list(GET _ctoks 0 _scpp)
                set_property(GLOBAL PROPERTY CPPTYPE_${_stype} "${_scpp}")
                list(LENGTH _ctoks _nct)
                if(_nct GREATER 1)
                    list(SUBLIST _ctoks 1 -1 _overrides)
                    foreach(_ov ${_overrides})
                        if(_ov MATCHES "^([A-Za-z0-9_]+)=([A-Za-z0-9_]+)(\\|(.+))?$")
                            set_property(GLOBAL PROPERTY CPPMEMBER_${_stype}_${CMAKE_MATCH_1} "${CMAKE_MATCH_2}")
                            if(NOT "${CMAKE_MATCH_4}" STREQUAL "")
                                set_property(GLOBAL PROPERTY CPPSPECIAL_${_stype}_${CMAKE_MATCH_1} "${CMAKE_MATCH_4}")
                            endif()
                        elseif(_ov MATCHES "^([A-Za-z0-9_]+)\\|(.+)$")
                            set_property(GLOBAL PROPERTY CPPSPECIAL_${_stype}_${CMAKE_MATCH_1} "${CMAKE_MATCH_2}")
                        endif()
                    endforeach()
                endif()
            endif()
            if(NOT "${_sfields}" STREQUAL "")
                _parse_fields("${_sfields}" "structs.${si}" "fields")
            endif()

        elseif(section STREQUAL "callbacks")
            if(NOT line MATCHES "^([A-Za-z0-9_]+) ?(.*) = ([A-Za-z0-9_]+)$")
                continue()
            endif()
            set(args "${CMAKE_MATCH_2}")
            set(cbtype "${CMAKE_MATCH_3}")
            get_property(cblist GLOBAL PROPERTY callbacks)
            list(LENGTH cblist ni)
            set(pfx "callbacks.${ni}")
            set_property(GLOBAL APPEND PROPERTY callbacks "${pfx}")
            set_property(GLOBAL PROPERTY ${pfx}.name "${cbtype}")
            string(REGEX REPLACE "Callback$" "" _cbbase "${cbtype}")
            _snake("${_cbbase}" _cbsnake)
            set_property(GLOBAL PROPERTY ${pfx}.method "on_${_cbsnake}")
            set_property(GLOBAL PROPERTY CBIDX_${cbtype} "${ni}")
            _parse_fields("${args}" "${pfx}" "params")

        elseif(section STREQUAL "functions")
            if(NOT line MATCHES "^([A-Za-z0-9_]+)\\.([A-Za-z0-9_]+) ?(.*) = (.+)$")
                continue()
            endif()
            set(cls "${CMAKE_MATCH_1}")
            set(meth "${CMAKE_MATCH_2}")
            set(args "${CMAKE_MATCH_3}")
            set(ret "${CMAKE_MATCH_4}")
            set(stat "")
            set(async "")
            if(ret MATCHES "^Static<(.+)>$")
                set(stat "1")
                set(ret "${CMAKE_MATCH_1}")
            endif()
            if(ret MATCHES "^Async<(.+)>$")
                set(async "1")
                set(ret "${CMAKE_MATCH_1}")
            endif()

            get_property(ci GLOBAL PROPERTY CLASSIDX_${cls})
            if("${ci}" STREQUAL "")
                get_property(clist GLOBAL PROPERTY classes)
                list(LENGTH clist ci)
                set_property(GLOBAL APPEND PROPERTY classes "classes.${ci}")
                set_property(GLOBAL PROPERTY CLASSIDX_${cls} "${ci}")
                set_property(GLOBAL PROPERTY classes.${ci}.name "${cls}")
                _cpp_class("${cls}" cpp)
                set_property(GLOBAL PROPERTY classes.${ci}.cpp "${cpp}")
                set_property(GLOBAL PROPERTY MCOUNT_${ci} "0")
            endif()
            get_property(mi GLOBAL PROPERTY MCOUNT_${ci})
            set(pfx "classes.${ci}.methods.${mi}")
            set_property(GLOBAL APPEND PROPERTY classes.${ci}.methods "${pfx}")
            set_property(GLOBAL PROPERTY ${pfx}.name "${meth}")
            set_property(GLOBAL PROPERTY ${pfx}.static "${stat}")
            set_property(GLOBAL PROPERTY ${pfx}.async "${async}")
            set_property(GLOBAL PROPERTY ${pfx}.ret "${ret}")
            if(ret STREQUAL "Void")
                set_property(GLOBAL PROPERTY ${pfx}.isvoid "1")
            elseif(ret STREQUAL "string")
                set_property(GLOBAL PROPERTY ${pfx}.retstring "1")
            elseif(ret STREQUAL "bytes")
                set_property(GLOBAL PROPERTY ${pfx}.retbytes "1")
            elseif(ret MATCHES "^Vector<(.+)>$")
                set_property(GLOBAL PROPERTY ${pfx}.retvector "1")
                _ntl_cpp("${CMAKE_MATCH_1}" _rvelc)
                set_property(GLOBAL PROPERTY ${pfx}.retelcpp "${_rvelc}")
            elseif(ret MATCHES "^Map<([^,]+), *(.+)>$")
                set(_mk "${CMAKE_MATCH_1}")
                set(_mv "${CMAKE_MATCH_2}")
                set_property(GLOBAL PROPERTY ${pfx}.retmap "1")
                set_property(GLOBAL PROPERTY ${pfx}.retmapkey "${_mk}")
                set_property(GLOBAL PROPERTY ${pfx}.retmapval "${_mv}")
                string(REGEX REPLACE "^.*\\." "" _mvb "${_mv}")
                get_property(_seen GLOBAL PROPERTY MAPSEEN_${_mvb})
                if("${_seen}" STREQUAL "")
                    set_property(GLOBAL PROPERTY MAPSEEN_${_mvb} "1")
                    get_property(_ml GLOBAL PROPERTY mapentries)
                    list(LENGTH _ml _mi)
                    set(_mpfx "mapentries.${_mi}")
                    set_property(GLOBAL APPEND PROPERTY mapentries "${_mpfx}")
                    set_property(GLOBAL PROPERTY ${_mpfx}.keytl "${_mk}")
                    set_property(GLOBAL PROPERTY ${_mpfx}.valtl "${_mv}")
                endif()
            elseif(ret MATCHES "^(int8|uint8|int16|uint16|int|uint|long|ulong|bool|double)$")
                set_property(GLOBAL PROPERTY ${pfx}.retscalar "1")
            endif()
            if(args MATCHES "Function<([A-Za-z0-9_]+)>")
                set_property(GLOBAL PROPERTY ${pfx}.iscb "1")
                set_property(GLOBAL PROPERTY ${pfx}.cbtype "${CMAKE_MATCH_1}")
                string(REGEX REPLACE "Function<([A-Za-z0-9_]+)>" "\\1" args "${args}")
            endif()
            _parse_fields("${args}" "${pfx}" "params")
            math(EXPR mi "${mi}+1")
            set_property(GLOBAL PROPERTY MCOUNT_${ci} "${mi}")
        endif()
    endwhile()

    _ntl_enrich()
endfunction()

function(_ntl_enrich)
    get_property(structs GLOBAL PROPERTY structs)
    foreach(s ${structs})
        get_property(_sn GLOBAL PROPERTY ${s}.name)
        set_property(GLOBAL PROPERTY SORDER_NAME_${_sn} "${s}")
    endforeach()
    foreach(s ${structs})
        get_property(nm GLOBAL PROPERTY ${s}.name)
        get_property(_ct GLOBAL PROPERTY CPPTYPE_${nm})
        if(NOT "${_ct}" STREQUAL "")
            set_property(GLOBAL PROPERTY ${s}.cpp "${_ct}")
        endif()
        get_property(fields GLOBAL PROPERTY ${s}.fields)
        list(LENGTH fields _nf)
        math(EXPR _lastf "${_nf}-1")
        set(_fi 0)
        foreach(f ${fields})
            get_property(fn GLOBAL PROPERTY ${f}.name)
            get_property(ft GLOBAL PROPERTY ${f}.type)
            get_property(fopt GLOBAL PROPERTY ${f}.optional)
            get_property(_mc GLOBAL PROPERTY CPPMEMBER_${nm}_${fn})
            if(NOT "${_mc}" STREQUAL "")
                set_property(GLOBAL PROPERTY ${f}.cpp "${_mc}")
            else()
                set_property(GLOBAL PROPERTY ${f}.cpp "${fn}")
            endif()

            if(ft STREQUAL "bytes")
                set_property(GLOBAL PROPERTY ${f}.bytes "1")
            elseif(ft MATCHES "^([a-z][a-z0-9_]*)\\.([A-Za-z0-9_]+)$")
                get_property(_ect GLOBAL PROPERTY CPPTYPE_${CMAKE_MATCH_2})
                if("${_ect}" STREQUAL "")
                    set_property(GLOBAL PROPERTY ${f}.intenum "${CMAKE_MATCH_1}::${CMAKE_MATCH_2}")
                endif()
            endif()

            _ntl_cpp("${ft}" _fcpp)
            set_property(GLOBAL PROPERTY ${f}.cpptype "${_fcpp}")
            if(ft MATCHES "^(int8|uint8|int16|uint16|int|uint|long|ulong|bool|double)$")
                set_property(GLOBAL PROPERTY ${f}.scalar "1")
            elseif(ft STREQUAL "string")
                set_property(GLOBAL PROPERTY ${f}.string "1")
            elseif(ft MATCHES "^Vector<(.+)>$")
                set_property(GLOBAL PROPERTY ${f}.vector "1")
                _ntl_cpp("${CMAKE_MATCH_1}" _elc)
                set_property(GLOBAL PROPERTY ${f}.elcpp "${_elc}")
            else()
                string(REGEX REPLACE "^.*\\." "" _fbase "${ft}")
                get_property(_fst GLOBAL PROPERTY SORDER_NAME_${_fbase})
                if(NOT "${_fst}" STREQUAL "")
                    set_property(GLOBAL PROPERTY ${f}.isstruct "1")
                endif()
            endif()

            set(_ap "${s}.ctorargs.${_fi}")
            set_property(GLOBAL APPEND PROPERTY ${s}.ctorargs "${_ap}")
            set_property(GLOBAL PROPERTY ${_ap}.name "${fn}")
            if(_fi EQUAL _lastf)
                set_property(GLOBAL PROPERTY ${_ap}.sep "")
            else()
                set_property(GLOBAL PROPERTY ${_ap}.sep ",")
            endif()
            if(fopt)
                set_property(GLOBAL PROPERTY ${_ap}.optional "1")
            endif()
            _enrich_arg("${_ap}" "${ft}" "${fopt}")
            math(EXPR _fi "${_fi}+1")
        endforeach()
    endforeach()

    get_property(_pclasses GLOBAL PROPERTY classes)
    foreach(_pc ${_pclasses})
        get_property(_pmethods GLOBAL PROPERTY ${_pc}.methods)
        foreach(_pm ${_pmethods})
            get_property(_pps GLOBAL PROPERTY ${_pm}.params)
            set(_pmhasconv "")
            foreach(_pp ${_pps})
                get_property(_ppt GLOBAL PROPERTY ${_pp}.type)
                _ntl_cpp("${_ppt}" _ppcpp)
                set_property(GLOBAL PROPERTY ${_pp}.cpptype "${_ppcpp}")
                if(_ppt STREQUAL "bytes")
                    set_property(GLOBAL PROPERTY ${_pp}.bytes "1")
                elseif(_ppt STREQUAL "string")
                    set_property(GLOBAL PROPERTY ${_pp}.string "1")
                elseif(_ppt MATCHES "^Vector<(.+)>$")
                    set_property(GLOBAL PROPERTY ${_pp}.vector "1")
                    _ntl_cpp("${CMAKE_MATCH_1}" _ppelc)
                    set_property(GLOBAL PROPERTY ${_pp}.elcpp "${_ppelc}")
                    set(_pmhasconv "1")
                elseif(_ppt MATCHES "^(int8|uint8|int16|uint16|int|uint|long|ulong|bool|double)$")
                    set_property(GLOBAL PROPERTY ${_pp}.scalar "1")
                else()
                    string(REGEX REPLACE "^.*\\." "" _ppbase "${_ppt}")
                    get_property(_ppsn GLOBAL PROPERTY SORDER_NAME_${_ppbase})
                    if(NOT "${_ppsn}" STREQUAL "")
                        set_property(GLOBAL PROPERTY ${_pp}.isstruct "1")
                        set(_pmhasconv "1")
                    endif()
                endif()
            endforeach()
            if(_pmhasconv)
                set_property(GLOBAL PROPERTY ${_pm}.hasconv "1")
            endif()
            get_property(_pmret GLOBAL PROPERTY ${_pm}.ret)
            string(REGEX REPLACE "^.*\\." "" _pmretbase "${_pmret}")
            get_property(_pmretsn GLOBAL PROPERTY SORDER_NAME_${_pmretbase})
            if(NOT "${_pmretsn}" STREQUAL "")
                set_property(GLOBAL PROPERTY ${_pm}.retstruct "1")
            endif()
        endforeach()
    endforeach()

    get_property(cbs GLOBAL PROPERTY callbacks)
    foreach(cb ${cbs})
        get_property(cn GLOBAL PROPERTY ${cb}.name)
        get_property(_ps GLOBAL PROPERTY ${cb}.params)
        list(LENGTH _ps _np)
        math(EXPR _lastp "${_np}-1")
        set(_ai 0)
        foreach(_p ${_ps})
            get_property(_pn GLOBAL PROPERTY ${_p}.name)
            get_property(_pt GLOBAL PROPERTY ${_p}.type)
            set(_ap "${cb}.cbargs.${_ai}")
            set_property(GLOBAL APPEND PROPERTY ${cb}.cbargs "${_ap}")
            set_property(GLOBAL PROPERTY ${_ap}.name "${_pn}")
            set_property(GLOBAL PROPERTY ${_ap}.type "${_pt}")
            if(_ai EQUAL _lastp)
                set_property(GLOBAL PROPERTY ${_ap}.sep "")
            else()
                set_property(GLOBAL PROPERTY ${_ap}.sep ",")
            endif()
            if(_pt STREQUAL "bytes")
                set_property(GLOBAL PROPERTY ${_ap}.bytes "1")
            elseif(_pt STREQUAL "string")
                set_property(GLOBAL PROPERTY ${_ap}.string "1")
            elseif(_pt MATCHES "^Vector<(.+)>$")
                set_property(GLOBAL PROPERTY ${_ap}.vector "1")
            elseif(_pt MATCHES "^(int8|uint8|int16|uint16|int|uint|long|ulong|bool|double)$")
                set_property(GLOBAL PROPERTY ${_ap}.scalar "1")
            else()
                string(REGEX REPLACE "^.*\\." "" _abase "${_pt}")
                get_property(_sname GLOBAL PROPERTY SORDER_NAME_${_abase})
                if(NOT "${_sname}" STREQUAL "")
                    set_property(GLOBAL PROPERTY ${_ap}.isstruct "1")
                endif()
            endif()
            _ntl_scalar_cpp("${_pt}" _psc)
            if(NOT "${_psc}" STREQUAL "")
                set_property(GLOBAL PROPERTY ${_ap}.cpptype "${_psc}")
            elseif(_pt STREQUAL "bytes")
                get_property(_bk GLOBAL PROPERTY CPPSPECIAL_${cn}_${_pn})
                if("${_bk}" STREQUAL "")
                    set(_bk "bytes::binary")
                endif()
                set_property(GLOBAL PROPERTY ${_ap}.cpptype "const ${_bk}&")
            else()
                _ntl_cpp("${_pt}" _pcpp)
                set_property(GLOBAL PROPERTY ${_ap}.cpptype "const ${_pcpp}&")
            endif()
            math(EXPR _ai "${_ai}+1")
        endforeach()
    endforeach()

    get_property(_classes GLOBAL PROPERTY classes)
    foreach(_c ${_classes})
        get_property(_methods GLOBAL PROPERTY ${_c}.methods)
        foreach(_m ${_methods})
            get_property(_ret GLOBAL PROPERTY ${_m}.ret)
            if(_ret STREQUAL "bytes")
                set_property(GLOBAL PROPERTY ${_m}.retbytes "1")
            endif()
            get_property(_ps GLOBAL PROPERTY ${_m}.params)
            list(LENGTH _ps _np)
            if(_np GREATER 0)
                set_property(GLOBAL PROPERTY ${_m}.argsep ",")
            endif()
            math(EXPR _lastp "${_np}-1")
            set(_ai 0)
            foreach(_p ${_ps})
                get_property(_pn GLOBAL PROPERTY ${_p}.name)
                get_property(_pt GLOBAL PROPERTY ${_p}.type)
                get_property(_popt GLOBAL PROPERTY ${_p}.optional)
                set(_ap "${_m}.args.${_ai}")
                set_property(GLOBAL APPEND PROPERTY ${_m}.args "${_ap}")
                set_property(GLOBAL PROPERTY ${_ap}.name "${_pn}")
                if(_ai EQUAL _lastp)
                    set_property(GLOBAL PROPERTY ${_ap}.sep "")
                else()
                    set_property(GLOBAL PROPERTY ${_ap}.sep ",")
                endif()
                if(_popt)
                    set_property(GLOBAL PROPERTY ${_ap}.optional "1")
                endif()
                _enrich_arg("${_ap}" "${_pt}" "${_popt}")
                math(EXPR _ai "${_ai}+1")
            endforeach()
        endforeach()
    endforeach()

    _ntl_order_structs()
    _ntl_order_excs()
endfunction()

function(_ntl_order_excs)
    get_property(_xs GLOBAL PROPERTY excs)
    set(_ordered "")
    set(_ri 0)
    foreach(x ${_xs})
        get_property(_xp GLOBAL PROPERTY ${x}.parent)
        if("${_xp}" STREQUAL "")
            math(EXPR _ri "${_ri}+1")
            math(EXPR _base "${_ri}*100")
            math(EXPR _rootcode "0 - ${_base}")
            set_property(GLOBAL PROPERTY ${x}.code "${_rootcode}")
            list(APPEND _ordered "${x}")
            get_property(_rname GLOBAL PROPERTY ${x}.name)
            set(_ci 0)
            foreach(y ${_xs})
                get_property(_yp GLOBAL PROPERTY ${y}.parent)
                if("${_yp}" STREQUAL "${_rname}")
                    math(EXPR _ci "${_ci}+1")
                    math(EXPR _childcode "0 - (${_base} + ${_ci})")
                    set_property(GLOBAL PROPERTY ${y}.code "${_childcode}")
                    list(APPEND _ordered "${y}")
                endif()
            endforeach()
        endif()
    endforeach()
    set_property(GLOBAL PROPERTY excs "${_ordered}")
endfunction()

function(_ntl_visit_struct s)
    get_property(_v GLOBAL PROPERTY SVISIT_${s})
    if(_v)
        return()
    endif()
    set_property(GLOBAL PROPERTY SVISIT_${s} "1")
    get_property(_fields GLOBAL PROPERTY ${s}.fields)
    foreach(f ${_fields})
        get_property(_fv GLOBAL PROPERTY ${f}.vector)
        get_property(_fs GLOBAL PROPERTY ${f}.scalar)
        get_property(_fstr GLOBAL PROPERTY ${f}.string)
        get_property(_fb GLOBAL PROPERTY ${f}.bytes)
        if(_fv OR _fs OR _fstr OR _fb)
            continue()
        endif()
        get_property(_ft GLOBAL PROPERTY ${f}.type)
        string(REGEX REPLACE "^.*\\." "" _ftn "${_ft}")
        get_property(_dep GLOBAL PROPERTY SORDER_NAME_${_ftn})
        if(NOT "${_dep}" STREQUAL "")
            _ntl_visit_struct("${_dep}")
        endif()
    endforeach()
    set_property(GLOBAL APPEND PROPERTY SORDERED "${s}")
endfunction()

function(_ntl_order_structs)
    get_property(_ss GLOBAL PROPERTY structs)
    foreach(s ${_ss})
        get_property(_n GLOBAL PROPERTY ${s}.name)
        set_property(GLOBAL PROPERTY SORDER_NAME_${_n} "${s}")
    endforeach()
    set_property(GLOBAL PROPERTY SORDERED "")
    foreach(s ${_ss})
        _ntl_visit_struct("${s}")
    endforeach()
    get_property(_ord GLOBAL PROPERTY SORDERED)
    set_property(GLOBAL PROPERTY structs "${_ord}")
endfunction()
