
function(_rule_add bank from to)
    get_property(_n GLOBAL PROPERTY ${bank}_N)
    if("${_n}" STREQUAL "")
        set(_n 0)
    endif()
    set_property(GLOBAL PROPERTY ${bank}_${_n}_from "${from}")
    set_property(GLOBAL PROPERTY ${bank}_${_n}_to "${to}")
    math(EXPR _n "${_n}+1")
    set_property(GLOBAL PROPERTY ${bank}_N "${_n}")
endfunction()

function(_flt_snake in out)
    string(REGEX REPLACE "([a-z])([A-Z])" "\\1_\\2" s "${in}")
    string(REGEX REPLACE "([A-Z][A-Z]+)([A-Z][a-z])" "\\1_\\2" s "${s}")
    string(REGEX REPLACE "([0-9])([A-Z][a-z])" "\\1_\\2" s "${s}")
    string(TOLOWER "${s}" s)
    set(${out} "${s}" PARENT_SCOPE)
endfunction()
function(_flt_camel in out)
    string(REPLACE "_" ";" parts "${in}")
    set(r "")
    set(first 1)
    foreach(p ${parts})
        if(first)
            set(r "${p}")
            set(first 0)
        else()
            string(SUBSTRING "${p}" 0 1 h)
            string(TOUPPER "${h}" h)
            string(SUBSTRING "${p}" 1 -1 t)
            string(APPEND r "${h}${t}")
        endif()
    endforeach()
    set(${out} "${r}" PARENT_SCOPE)
endfunction()
function(_flt_type value boxed out)
    if(boxed)
        get_property(_bn GLOBAL PROPERTY BOXMAP_N)
        if("${_bn}" STREQUAL "")
            set(_bn 0)
        endif()
        set(_bi 0)
        while(_bi LESS _bn)
            get_property(_from GLOBAL PROPERTY BOXMAP_${_bi}_from)
            get_property(_to GLOBAL PROPERTY BOXMAP_${_bi}_to)
            if(value STREQUAL "${_from}")
                set(${out} "${_to}" PARENT_SCOPE)
                return()
            endif()
            math(EXPR _bi "${_bi}+1")
        endwhile()
    endif()
    get_property(_tn GLOBAL PROPERTY TYPEMAP_N)
    if("${_tn}" STREQUAL "")
        set(_tn 0)
    endif()
    set(_ti 0)
    while(_ti LESS _tn)
        get_property(_from GLOBAL PROPERTY TYPEMAP_${_ti}_from)
        get_property(_to GLOBAL PROPERTY TYPEMAP_${_ti}_to)
        math(EXPR _ti "${_ti}+1")
        if(_from MATCHES "\\*")
            string(REGEX MATCHALL "\\*" _stars "${_from}")
            list(LENGTH _stars _ns)
            string(REPLACE "*" "(.+)" _rx "${_from}")
            if(value MATCHES "^${_rx}$")
                set(_caps "")
                foreach(_k RANGE 1 ${_ns})
                    list(APPEND _caps "${CMAKE_MATCH_${_k}}")
                endforeach()
                set(_res "${_to}")
                foreach(_cap ${_caps})
                    string(FIND "${_res}" "*" _sp)
                    if(_sp LESS 0)
                        break()
                    endif()
                    if(_from MATCHES "<")
                        _flt_type("${_cap}" "1" _m)
                    else()
                        set(_m "${_cap}")
                    endif()
                    string(SUBSTRING "${_res}" 0 ${_sp} _pre)
                    math(EXPR _spa "${_sp}+1")
                    string(SUBSTRING "${_res}" ${_spa} -1 _post)
                    set(_res "${_pre}${_m}${_post}")
                endforeach()
                set(${out} "${_res}" PARENT_SCOPE)
                return()
            endif()
        elseif(value STREQUAL "${_from}")
            set(${out} "${_to}" PARENT_SCOPE)
            return()
        endif()
    endwhile()
    string(REGEX REPLACE "^.*\\." "" v "${value}")
    set(${out} "${v}" PARENT_SCOPE)
endfunction()

function(_conv mapname typeval value out)
    string(REGEX REPLACE "^.*\\." "" _simple "${typeval}")
    get_property(_n GLOBAL PROPERTY WRAPMAP_${mapname}_N)
    if("${_n}" STREQUAL "")
        set(_n 0)
    endif()
    set(_i 0)
    while(_i LESS _n)
        get_property(_from GLOBAL PROPERTY WRAPMAP_${mapname}_${_i}_from)
        get_property(_to GLOBAL PROPERTY WRAPMAP_${mapname}_${_i}_to)
        math(EXPR _i "${_i}+1")
        set(_m 0)
        if(_from STREQUAL "*")
            set(_m 1)
        elseif(_from MATCHES "\\*")
            string(REPLACE "*" "(.+)" _rx "${_from}")
            if(typeval MATCHES "^${_rx}$")
                set(_m 1)
            endif()
        elseif(typeval STREQUAL "${_from}")
            set(_m 1)
        endif()
        if(_m)
            string(REPLACE "." "/" _slashed "${typeval}")
            string(REPLACE "$" "${value}" _to "${_to}")
            string(REPLACE "#" "${_simple}" _to "${_to}")
            string(REPLACE "@" "${_slashed}" _to "${_to}")
            set(${out} "${_to}" PARENT_SCOPE)
            return()
        endif()
    endwhile()
    set(${out} "${value}" PARENT_SCOPE)
endfunction()

function(_apply_filter value filter out)
    if(filter MATCHES "^conv#([A-Za-z0-9_]+)#(.+)$")
        _resolve("${CMAKE_MATCH_2}" _tv)
        _conv("${CMAKE_MATCH_1}" "${_tv}" "${value}" v)
    elseif(filter STREQUAL "type")
        _flt_type("${value}" "" v)
    elseif(filter STREQUAL "snake")
        _flt_snake("${value}" v)
    elseif(filter STREQUAL "camel")
        _flt_camel("${value}" v)
    elseif(filter STREQUAL "upper")
        string(TOUPPER "${value}" v)
    elseif(filter STREQUAL "lower")
        string(TOLOWER "${value}" v)
    elseif(filter STREQUAL "base")
        string(REGEX REPLACE "^.*::" "" v "${value}")
        string(REGEX REPLACE "^.*\\." "" v "${v}")
    elseif(filter STREQUAL "slash")
        string(REPLACE "." "/" v "${value}")
    elseif(filter STREQUAL "reserve")
        get_property(_rw GLOBAL PROPERTY config.reserved)
        string(REPLACE " " ";" _rwl "${_rw}")
        list(FIND _rwl "${value}" _ridx)
        if(_ridx GREATER -1)
            get_property(_rp GLOBAL PROPERTY config.reserve_prefix)
            set(v "${_rp}${value}")
        else()
            set(v "${value}")
        endif()
    elseif(filter STREQUAL "pascal")
        _flt_snake("${value}" s)
        set(v "")
        string(REPLACE "_" ";" parts "${s}")
        foreach(p ${parts})
            string(SUBSTRING "${p}" 0 1 h)
            string(TOUPPER "${h}" h)
            string(SUBSTRING "${p}" 1 -1 t)
            string(APPEND v "${h}${t}")
        endforeach()
    else()
        set(v "${value}")
    endif()
    set(${out} "${v}" PARENT_SCOPE)
endfunction()

function(_resolve path out)
    string(FIND "${path}" "." dot)
    if(dot GREATER -1)
        string(SUBSTRING "${path}" 0 ${dot} head)
        math(EXPR r "${dot}+1")
        string(SUBSTRING "${path}" ${r} -1 rest)
    else()
        set(head "${path}")
set(rest "")
    endif()
    get_property(bind GLOBAL PROPERTY "BIND_${head}")
    if(bind)
        if("${rest}" STREQUAL "")
            set(real "${bind}")
        else()
            set(real "${bind}.${rest}")
        endif()
    else()
        set(real "${path}")
    endif()
    get_property(val GLOBAL PROPERTY "${real}")
    set(${out} "${val}" PARENT_SCOPE)
    set(${out}_REAL "${real}" PARENT_SCOPE)
endfunction()

function(_subst line out)
    set(res "${line}")
    while(res MATCHES "@\\{([^}]*)\\}")
        set(expr "${CMAKE_MATCH_1}")
        string(FIND "${expr}" "|" bar)
        if(bar GREATER -1)
            string(SUBSTRING "${expr}" 0 ${bar} path)
            math(EXPR r "${bar}+1")
string(SUBSTRING "${expr}" ${r} -1 filt)
        else()
            set(path "${expr}")
set(filt "")
        endif()
        _resolve("${path}" val)
        if(NOT "${filt}" STREQUAL "")
            string(REPLACE "|" ";" _filts "${filt}")
            foreach(_f ${_filts})
                _apply_filter("${val}" "${_f}" val)
            endforeach()
        endif()
        string(REPLACE "@{${expr}}" "${val}" res "${res}")
    endwhile()
    set(${out} "${res}" PARENT_SCOPE)
endfunction()

function(_process_imports content out)
    get_property(roots GLOBAL PROPERTY IMPORTROOTS)
    get_property(sep GLOBAL PROPERTY config.import_sep)
    get_property(stmt GLOBAL PROPERTY config.import_line)
    get_property(anchor GLOBAL PROPERTY config.import_anchor)
    if("${sep}" STREQUAL "" OR "${stmt}" STREQUAL "" OR "${anchor}" STREQUAL "")
        message(FATAL_ERROR "@importroot requires config.import_sep, config.import_line and config.import_anchor to be set (use import_anchor = - to disable module detection)")
    endif()
    string(REPLACE "." "\\." _sepx "${sep}")

    set(filepkg "")
    if(NOT "${anchor}" STREQUAL "-" AND content MATCHES "${anchor} ([^;\n]+) *;")
        set(filepkg "${CMAKE_MATCH_1}")
    endif()
    set(allfqns "")
    foreach(root ${roots})
        string(REPLACE "." "\\." _rr "${root}")
        string(REGEX MATCHALL "${_rr}(${_sepx}[a-z][A-Za-z0-9_]*)*${_sepx}[A-Z][A-Za-z0-9_]*" _fq "${content}")
        list(APPEND allfqns ${_fq})
    endforeach()
    if(allfqns)
        list(REMOVE_DUPLICATES allfqns)
        list(SORT allfqns)
    endif()
    set(impblock "")
    foreach(fq ${allfqns})
        string(REGEX REPLACE "${_sepx}[A-Z][A-Za-z0-9_]*$" "" fqpkg "${fq}")
        string(REGEX REPLACE "^.*${_sepx}" "" simple "${fq}")
        string(REPLACE "${fq}" "${simple}" content "${content}")
        if(NOT "${fqpkg}" STREQUAL "${filepkg}")
            string(REPLACE "$" "${fq}" _line "${stmt}")
            string(APPEND impblock "${_line}\n")
        endif()
    endforeach()
    if("${impblock}" STREQUAL "")
        set(${out} "${content}" PARENT_SCOPE)
        return()
    endif()
    if(NOT "${filepkg}" STREQUAL "")
        string(REPLACE "${anchor} ${filepkg};\n" "${anchor} ${filepkg};\n\n${impblock}" content "${content}")
    else()
        set(content "${impblock}\n${content}")
    endif()
    set(${out} "${content}" PARENT_SCOPE)
endfunction()

function(_render a b)
    set(i ${a})
    while(NOT i GREATER b)
        get_property(_skip GLOBAL PROPERTY RENDER_SKIP)
        if(_skip)
            break()
        endif()
        get_property(line GLOBAL PROPERTY TPL_${i})
        string(STRIP "${line}" trimmed)
        if(trimmed MATCHES "^@for ([A-Za-z0-9_]+) in ([A-Za-z0-9_.]+)$")
            set(var "${CMAKE_MATCH_1}")
set(coll "${CMAKE_MATCH_2}")
            get_property(endi GLOBAL PROPERTY JMP_${i})
            _resolve("${coll}" items)
            get_property(oldbind GLOBAL PROPERTY "BIND_${var}")
            math(EXPR bodyA "${i}+1")
math(EXPR bodyB "${endi}-1")
            foreach(item ${items})
                set_property(GLOBAL PROPERTY "BIND_${var}" "${item}")
                _render(${bodyA} ${bodyB})
                set_property(GLOBAL PROPERTY RENDER_SKIP "")
            endforeach()
            set_property(GLOBAL PROPERTY "BIND_${var}" "${oldbind}")
            set(i ${endi})
        elseif(trimmed MATCHES "^@ifany [A-Za-z0-9_]+ in ([A-Za-z0-9_.]+) : ([A-Za-z0-9_]+)$")
            set(anycoll "${CMAKE_MATCH_1}")
            set(anyfld "${CMAKE_MATCH_2}")
            get_property(endi GLOBAL PROPERTY JMP_${i})
            get_property(elsei GLOBAL PROPERTY ELSE_${i})
            _resolve("${anycoll}" anyitems)
            set(truthy FALSE)
            foreach(anyit ${anyitems})
                get_property(anyv GLOBAL PROPERTY "${anyit}.${anyfld}")
                if(NOT ("${anyv}" STREQUAL "" OR anyv STREQUAL "0" OR anyv STREQUAL "false" OR anyv STREQUAL "OFF"))
                    set(truthy TRUE)
                    break()
                endif()
            endforeach()
            math(EXPR bodyA "${i}+1")
            if(elsei)
                if(truthy)
                    math(EXPR bb "${elsei}-1")
_render(${bodyA} ${bb})
                else()
                    math(EXPR ea "${elsei}+1")
math(EXPR eb "${endi}-1")
_render(${ea} ${eb})
                endif()
            elseif(truthy)
                math(EXPR bb "${endi}-1")
_render(${bodyA} ${bb})
            endif()
            set(i ${endi})
        elseif(trimmed MATCHES "^@skip ([A-Za-z0-9_.]+) in (.+)$")
            _resolve("${CMAKE_MATCH_1}" _sv)
            string(REPLACE "," ";" _slist "${CMAKE_MATCH_2}")
            foreach(_se ${_slist})
                string(STRIP "${_se}" _se)
                if(_sv STREQUAL "${_se}")
                    set_property(GLOBAL PROPERTY RENDER_SKIP 1)
                endif()
            endforeach()
        elseif(trimmed MATCHES "^@if ([A-Za-z0-9_.]+)$")
            set(cond "${CMAKE_MATCH_1}")
            get_property(endi GLOBAL PROPERTY JMP_${i})
            get_property(elsei GLOBAL PROPERTY ELSE_${i})
            _resolve("${cond}" val)
            set(truthy TRUE)
            if("${val}" STREQUAL "" OR val STREQUAL "0" OR val STREQUAL "false" OR val STREQUAL "OFF")
                set(truthy FALSE)
            endif()
            math(EXPR bodyA "${i}+1")
            if(elsei)
                if(truthy)
                    math(EXPR bb "${elsei}-1")
_render(${bodyA} ${bb})
                else()
                    math(EXPR ea "${elsei}+1")
math(EXPR eb "${endi}-1")
_render(${ea} ${eb})
                endif()
            elseif(truthy)
                math(EXPR bb "${endi}-1")
_render(${bodyA} ${bb})
            endif()
            set(i ${endi})
        elseif(trimmed MATCHES "^@typemap (.+) = (.+)$")
            _rule_add("TYPEMAP" "${CMAKE_MATCH_1}" "${CMAKE_MATCH_2}")
        elseif(trimmed MATCHES "^@boxmap (.+) = (.+)$")
            _rule_add("BOXMAP" "${CMAKE_MATCH_1}" "${CMAKE_MATCH_2}")
        elseif(trimmed MATCHES "^@wrapmap ([A-Za-z0-9_]+) (.+) = (.+)$")
            _rule_add("WRAPMAP_${CMAKE_MATCH_1}" "${CMAKE_MATCH_2}" "${CMAKE_MATCH_3}")
        elseif(trimmed MATCHES "^@importroot (.+)$")
            set_property(GLOBAL APPEND PROPERTY IMPORTROOTS "${CMAKE_MATCH_1}")
        elseif(trimmed MATCHES "^@config ([A-Za-z0-9_.]+) *= *(.*)$")
            _subst("${CMAKE_MATCH_2}" _cv)
            set_property(GLOBAL PROPERTY config.${CMAKE_MATCH_1} "${_cv}")
        elseif(trimmed MATCHES "^@out (.+)$")
            _subst("${CMAKE_MATCH_1}" _ov)
            set_property(GLOBAL PROPERTY RENDER_OUTFILE "${_ov}")
        elseif(trimmed MATCHES "^@file (.+)$")
            _subst("${CMAKE_MATCH_1}" fpath)
            set_property(GLOBAL PROPERTY RENDER_FILE "${fpath}")
            set_property(GLOBAL PROPERTY RENDER_FBUF "")
        elseif(trimmed STREQUAL "@endfile")
            get_property(rf GLOBAL PROPERTY RENDER_FILE)
            get_property(rb GLOBAL PROPERTY RENDER_FBUF)
            get_property(roots GLOBAL PROPERTY IMPORTROOTS)
            if(roots)
                _process_imports("${rb}" rb)
            endif()
            _emit_file("${rf}" "${rb}")
            set_property(GLOBAL PROPERTY RENDER_FILE "")
        else()
            _subst("${line}" out)
            get_property(rf GLOBAL PROPERTY RENDER_FILE)
            if("${rf}" STREQUAL "")
                get_property(acc GLOBAL PROPERTY RENDER_OUT)
                set_property(GLOBAL PROPERTY RENDER_OUT "${acc}${out}\n")
            else()
                get_property(acc GLOBAL PROPERTY RENDER_FBUF)
                set_property(GLOBAL PROPERTY RENDER_FBUF "${acc}${out}\n")
            endif()
        endif()
        math(EXPR i "${i}+1")
    endwhile()
endfunction()

function(_build_jumps n)
    set(stack "")
    set(i 0)
    while(i LESS n)
        set_property(GLOBAL PROPERTY JMP_${i} "")
        set_property(GLOBAL PROPERTY ELSE_${i} "")
        math(EXPR i "${i}+1")
    endwhile()
    set(i 0)
    while(i LESS n)
        get_property(line GLOBAL PROPERTY TPL_${i})
        string(STRIP "${line}" t)
        if(t MATCHES "^@for " OR t MATCHES "^@if " OR t MATCHES "^@ifany ")
            list(APPEND stack ${i})
        elseif(t STREQUAL "@else")
            list(GET stack -1 top)
            set_property(GLOBAL PROPERTY ELSE_${top} ${i})
        elseif(t STREQUAL "@end")
            list(GET stack -1 top)
            set_property(GLOBAL PROPERTY JMP_${top} ${i})
            list(REMOVE_AT stack -1)
        endif()
        math(EXPR i "${i}+1")
    endwhile()
endfunction()

function(_emit_file path content)
    if(path MATCHES "\\.(cpp|hpp|cc|cxx|h)$")
        set(content "// NOLINTBEGIN\n${content}// NOLINTEND\n")
    endif()
    get_property(_bnr GLOBAL PROPERTY config.banner)
    if(NOT "${_bnr}" STREQUAL "")
        set(content "${_bnr}\n${content}")
    endif()
    file(WRITE "${path}" "${content}")
endfunction()

function(render_template tpl_file)
    get_filename_component(_selfdir "${tpl_file}" DIRECTORY)
    set_property(GLOBAL PROPERTY config.self_dir "${_selfdir}")
    string(REGEX REPLACE "\\.tpl$" "" _defout "${tpl_file}")
    set_property(GLOBAL PROPERTY RENDER_OUTFILE "${_defout}")
    file(READ "${tpl_file}" content)
    set(n 0)
    while(NOT "${content}" STREQUAL "")
        string(FIND "${content}" "\n" nl)
        if(nl LESS 0)
            set_property(GLOBAL PROPERTY TPL_${n} "${content}")
            math(EXPR n "${n}+1")
            break()
        endif()
        string(SUBSTRING "${content}" 0 ${nl} line)
        set_property(GLOBAL PROPERTY TPL_${n} "${line}")
        math(EXPR n "${n}+1")
        math(EXPR after "${nl}+1")
        string(SUBSTRING "${content}" ${after} -1 content)
    endwhile()
    _build_jumps(${n})
    set_property(GLOBAL PROPERTY RENDER_OUT "")
    set_property(GLOBAL PROPERTY RENDER_FILE "")
    set_property(GLOBAL PROPERTY RENDER_SKIP "")
    set_property(GLOBAL PROPERTY TYPEMAP_N 0)
    set_property(GLOBAL PROPERTY BOXMAP_N 0)
    set_property(GLOBAL PROPERTY IMPORTROOTS "")
    math(EXPR last "${n}-1")
    _render(0 ${last})
    get_property(result GLOBAL PROPERTY RENDER_OUT)
    get_property(outfile GLOBAL PROPERTY RENDER_OUTFILE)
    if(NOT "${result}" STREQUAL "")
        get_property(roots GLOBAL PROPERTY IMPORTROOTS)
        if(roots)
            _process_imports("${result}" result)
        endif()
        _emit_file("${outfile}" "${result}")
    endif()
endfunction()
