set(NTGCALLS_LIB ${CMAKE_SOURCE_DIR}/ntgcalls/${ANDROID_ABI}/${CMAKE_STATIC_LIBRARY_PREFIX}ntgcalls${CMAKE_STATIC_LIBRARY_SUFFIX})
add_library(NTgCalls::ntgcalls UNKNOWN IMPORTED)
set_target_properties(
    NTgCalls::ntgcalls PROPERTIES
    INTERFACE_COMPILE_DEFINITIONS "${BASE_COMPILE_DEFINITIONS}"
    INTERFACE_COMPILE_OPTIONS "${BASE_COMPILE_OPTIONS}"
    INTERFACE_INCLUDE_DIRECTORIES "${NTGCALLS_INCLUDE_DIR}"
    INTERFACE_LINK_LIBRARIES "Wrtc::wrtc"
    IMPORTED_LOCATION "${NTGCALLS_LIB}"
)