set(WRTC_LIB ${CMAKE_SOURCE_DIR}/wrtc/${ANDROID_ABI}/${CMAKE_STATIC_LIBRARY_PREFIX}wrtc${CMAKE_STATIC_LIBRARY_SUFFIX})
add_library(Wrtc::wrtc UNKNOWN IMPORTED)
set_target_properties(
        Wrtc::wrtc PROPERTIES
        INTERFACE_INCLUDE_DIRECTORIES "${WRTC_INCLUDE_DIR}"
        IMPORTED_LOCATION "${WRTC_LIB}"
)