set(NTGCALLS_LIB ${CMAKE_SOURCE_DIR}/ntgcalls/${ANDROID_ABI}/${CMAKE_STATIC_LIBRARY_PREFIX}ntgcalls${CMAKE_STATIC_LIBRARY_SUFFIX})
add_library(NTgCalls::ntgcalls UNKNOWN IMPORTED)
set_target_properties(
    NTgCalls::ntgcalls PROPERTIES
    INTERFACE_INCLUDE_DIRECTORIES "${NTGCALLS_INCLUDE_DIR}"
    IMPORTED_LOCATION "${NTGCALLS_LIB}"
)