set(WRTC_LIB ${CMAKE_SOURCE_DIR}/wrtc/${ANDROID_ABI}/${CMAKE_STATIC_LIBRARY_PREFIX}wrtc${CMAKE_STATIC_LIBRARY_SUFFIX})
add_library(Wrtc::wrtc UNKNOWN IMPORTED)
set_target_properties(
    Wrtc::wrtc PROPERTIES
    INTERFACE_COMPILE_DEFINITIONS "${BASE_COMPILE_DEFINITIONS}"
    INTERFACE_COMPILE_OPTIONS "${BASE_COMPILE_OPTIONS}"
    INTERFACE_INCLUDE_DIRECTORIES "${WRTC_INCLUDE_DIR}"
    INTERFACE_LINK_LIBRARIES "WebRTC::webrtc"
    IMPORTED_LOCATION "${WRTC_LIB}"
)