FROM quay.io/pypa/manylinux2014_x86_64:latest
RUN yum install -y \
    alsa-lib-devel \
    pulseaudio-libs-devel \
    mesa-libgbm-devel \
    libXcomposite-devel \
    libXrandr-devel \
    libXtst-devel
