@ECHO OFF
SET EL=0

ECHO Add depot_tools to PATH
set PATH=%DEPOT_TOOLS%;%PATH%
IF %ERRORLEVEL% NEQ 0 GOTO ERROR

ECHO cd SOURCE_DIR
cd %SOURCE_DIR%
IF %ERRORLEVEL% NEQ 0 GOTO ERROR

ECHO APPLY PATCHES
SET PATCHES_DIR=%~dp0..\patches\
SET PATCHES_FILE=4k win_audio win_cxx win_deps

FOR %%f IN (%PATCHES_FILE%) DO (
  ECHO Applying patch %%f.patch...
  CALL git apply -p1 --ignore-space-change --ignore-whitespace --whitespace=nowarn %PATCHES_DIR%%%f.patch 2>&1 | exit 0
)

ECHO SET DEPOT_TOOLS_WIN_TOOLCHAIN
SET DEPOT_TOOLS_WIN_TOOLCHAIN=0
IF %ERRORLEVEL% NEQ 0 GOTO ERROR

ECHO gn gen BINARY_DIR "--args=GN_GEN_ARGS"
CALL gn gen %BINARY_DIR% "--args=%GN_GEN_ARGS%"
IF %ERRORLEVEL% NEQ 0 GOTO ERROR

GOTO DONE

:ERROR
ECHO ERRORLEVEL^: %ERRORLEVEL%
SET EL=%ERRORLEVEL%

:DONE

EXIT /b %EL%
