function(crc32_string INPUT OUT)
  string(LENGTH "${INPUT}" len)
  if(len EQUAL 0)
    set(${OUT} "0x00000000" PARENT_SCOPE)
    return()
  endif()
  set(crc 4294967295)
  math(EXPR last "${len} - 1")
  foreach(i RANGE 0 ${last})
    string(SUBSTRING "${INPUT}" ${i} 1 ch)
    string(HEX "${ch}" hex)
    math(EXPR byte "0x${hex}")
    math(EXPR crc "${crc} ^ ${byte}")
    foreach(k RANGE 0 7)
      math(EXPR mask "-(${crc} & 1)")
      math(EXPR crc "((${crc} >> 1) & 2147483647) ^ (${mask} & 3988292384)")
    endforeach()
  endforeach()
  math(EXPR crc "(${crc} ^ 4294967295) & 4294967295")
  math(EXPR hexout "${crc}" OUTPUT_FORMAT HEXADECIMAL)
  string(REGEX REPLACE "^0x" "" hexout "${hexout}")
  string(TOLOWER "${hexout}" hexout)
  string(LENGTH "${hexout}" hl)
  math(EXPR pad "8 - ${hl}")
  if(pad GREATER 0)
    string(REPEAT "0" ${pad} zeros)
    set(hexout "${zeros}${hexout}")
  endif()
  set(${OUT} "0x${hexout}" PARENT_SCOPE)
endfunction()
