include(${CMAKE_CURRENT_LIST_DIR}/CRC32.cmake)
GetProperty("version.e2e_tl" E2E_TL_COMMIT)

string(LENGTH "${E2E_TL_COMMIT}" e2e_tl_len)
if(e2e_tl_len GREATER 7)
    string(SUBSTRING "${E2E_TL_COMMIT}" 0 7 e2e_tl_short)
else()
    set(e2e_tl_short "${E2E_TL_COMMIT}")
endif()
message(STATUS "e2e-tl td@${e2e_tl_short}")
set(E2E_HEADER_DIR "${CMAKE_SOURCE_DIR}/ntgcalls/include/ntgcalls/tl/e2e_api.hpp")
set(E2E_SRC_DIR "${CMAKE_SOURCE_DIR}/ntgcalls/src/tl/e2e_api.cpp")
if (EXISTS ${E2E_HEADER_DIR} AND EXISTS ${E2E_SRC_DIR} AND "${E2E_LAST_GEN_COMMIT}" STREQUAL "${E2E_TL_COMMIT}")
    return()
endif ()

GitFile(
    URL https://github.com/tdlib/td/blob/${E2E_TL_COMMIT}/td/generate/scheme/e2e_api.tl
    OUTPUT_VARIABLE schema_file
)
string(REGEX REPLACE "\n--- functions ---.*$" "" schema_file "${schema_file}")
string(REPLACE "\r" "" schema_file "${schema_file}")

set(SKIP_TYPES
    int long double string bytes boolFalse boolTrue true vector
    int32 int53 int64 int128 int256 int512 secureBytes secureString ok
)
string(REPLACE "\n" ";" lines "${schema_file}")

set(CONSTRUCTOR_NAMES "")
foreach(line ${lines})
    string(STRIP "${line}" line)
    if(line STREQUAL "" OR line MATCHES "^//")
        continue()
    endif()
    if(NOT line MATCHES "^(.+) = ([^ ;]+);?$")
        continue()
    endif()
    set(lhs "${CMAKE_MATCH_1}")
    set(result "${CMAKE_MATCH_2}")
    if(NOT lhs MATCHES "^([A-Za-z0-9_.]+)(#([0-9a-fA-F]+))?(.*)$")
        continue()
    endif()
    set(name "${CMAKE_MATCH_1}")
    set(explicit_id "${CMAKE_MATCH_3}")
    set(fields "${CMAKE_MATCH_4}")
    string(STRIP "${fields}" fields)
    list(FIND SKIP_TYPES "${name}" skip_idx)
    if(skip_idx GREATER -1 OR lhs MATCHES "[{\\[]")
        continue()
    endif()
    if(fields STREQUAL "")
        continue()
    endif()
    list(APPEND CONSTRUCTOR_NAMES "${name}")
    set("CONSTRUCTOR_${name}_RESULT" "${result}")
    set("CONSTRUCTOR_${name}_EXPLICIT_ID" "${explicit_id}")
    set("CONSTRUCTOR_${name}_FIELDS" "${fields}")
endforeach ()

function(build_crc NAME OUT_VAR)
    set(s "${NAME}")
    set(fields "${CONSTRUCTOR_${NAME}_FIELDS}")
    if(NOT fields STREQUAL "")
        string(REPLACE " " ";" flist "${fields}")
        foreach(f ${flist})
            if(NOT f MATCHES "^([A-Za-z0-9_]+):(.+)$")
                message(FATAL_ERROR "Bad field '${f}' in ${NAME}")
            endif()
            set(fn "${CMAKE_MATCH_1}")
            set(ft "${CMAKE_MATCH_2}")
            if(ft MATCHES "^vector<(.+)>$")
                set(ft "vector ${CMAKE_MATCH_1}")
            endif()
            string(APPEND s " ${fn}:${ft}")
        endforeach ()
    endif ()
    string(APPEND s " = ${CONSTRUCTOR_${NAME}_RESULT}")
    crc32_string("${s}" id)
    set(${OUT_VAR} "${id}" PARENT_SCOPE)
endfunction()

foreach(name ${CONSTRUCTOR_NAMES})
    build_crc("${name}" computed)
    set(explicit_id "${CONSTRUCTOR_${name}_EXPLICIT_ID}")
    if(NOT explicit_id STREQUAL "")
        set(ex_pid "0x${explicit_id}")
        if(NOT computed STREQUAL "${ex_pid}")
            message(FATAL_ERROR "TL id oracle FAILED for ${name}: computed ${computed} != explicit ${ex_pid}")
        endif()
    endif ()
    set("CONSTRUCTOR_${name}_ID" "${computed}")
endforeach ()

list(LENGTH CONSTRUCTOR_NAMES CONSTRUCTOR_COUNT)

set(RESULT_TYPES "")
foreach(name ${CONSTRUCTOR_NAMES})
    set(r "${CONSTRUCTOR_${name}_RESULT}")
    list(FIND RESULT_TYPES "${r}" idx)
    if(idx EQUAL -1)
        list(APPEND RESULT_TYPES "${r}")
        set("RES_${r}_CONSTRUCTORS" "")
    endif()
    list(APPEND "RES_${r}_CONSTRUCTORS" "${name}")
endforeach ()

function(cap_first S OUT_VAR)
    if(S STREQUAL "")
        set(${OUT_VAR} "" PARENT_SCOPE)
        return()
    endif()
    string(SUBSTRING "${S}" 0 1 h)
    string(TOUPPER "${h}" h)
    string(SUBSTRING "${S}" 1 -1 rest)
    set(${OUT_VAR} "${h}${rest}" PARENT_SCOPE)
endfunction()

function(cpp_name NAME QUAL_VAR NAMESPACE_VAR SHORT_VAR)
    if(NAME MATCHES "^(.+)\\.([^.]+)$")
        string(REPLACE "." "::" namespace "${CMAKE_MATCH_1}")
        set(short "${CMAKE_MATCH_2}")
    else()
        set(namespace "")
        set(short "${NAME}")
    endif()
    cap_first("${short}" short)
    if(namespace STREQUAL "")
        set(qualified "${short}")
    else()
        set(qualified "${namespace}::${short}")
    endif()
    set(${QUAL_VAR} "${qualified}" PARENT_SCOPE)
    set(${NAMESPACE_VAR} "${namespace}" PARENT_SCOPE)
    set(${SHORT_VAR} "${short}" PARENT_SCOPE)
endfunction()

function(resolve_type TL_TYPE OUT_VAR)
    list(FIND RESULT_TYPES "${TL_TYPE}" ri)
    if(ri GREATER -1)
        set(constructors "${RES_${TL_TYPE}_CONSTRUCTORS}")
        list(LENGTH constructors count)
        if(count EQUAL 1)
            cpp_name("${constructors}" out x y)
        else()
            cpp_name("${TL_TYPE}" out x y)
        endif()
    else()
        cpp_name("${TL_TYPE}" out x y)
    endif()
    set(${OUT_VAR} "${out}" PARENT_SCOPE)
endfunction()

function(relative_name QUALIFIED CURRENT_NS OUT_VAR)
    if(QUALIFIED MATCHES "^(.+)::([^:]+)$")
        set(tns "${CMAKE_MATCH_1}")
        set(leaf "${CMAKE_MATCH_2}")
    else()
        set(${OUT_VAR} "${QUALIFIED}" PARENT_SCOPE)
        return()
    endif()
    set(enclosing "")
    set(cur "${CURRENT_NS}")
    while(TRUE)
        list(APPEND enclosing "${cur}")
        if(cur STREQUAL "")
            break()
        endif()
        if(cur MATCHES "^(.+)::[^:]+$")
            set(cur "${CMAKE_MATCH_1}")
        else()
            set(cur "")
        endif()
    endwhile()
    set(chosen "__none__")
    foreach(e ${enclosing})
        if(e STREQUAL "")
            set(chosen "")
            break()
        endif()
        if(tns STREQUAL "${e}" OR tns MATCHES "^${e}::")
            set(chosen "${e}")
            break()
        endif()
    endforeach()
    if(chosen STREQUAL "")
        set(remainder "${tns}")
    elseif(tns STREQUAL "${chosen}")
        set(remainder "")
    else()
        string(LENGTH "${chosen}::" plen)
        string(SUBSTRING "${tns}" ${plen} -1 remainder)
    endif()
    if(remainder STREQUAL "")
        set(${OUT_VAR} "${leaf}" PARENT_SCOPE)
    else()
        set(${OUT_VAR} "${remainder}::${leaf}" PARENT_SCOPE)
    endif()
endfunction()

function(base_map TYPE CPP_VAR STORE_VAR FETCH_VAR)
    if(TYPE STREQUAL "int" OR TYPE STREQUAL "int32" OR TYPE STREQUAL "#")
        set(${CPP_VAR} "int32_t" PARENT_SCOPE)
        set(${STORE_VAR} "store_int32" PARENT_SCOPE)
        set(${FETCH_VAR} "fetch_int32" PARENT_SCOPE)
    elseif(TYPE STREQUAL "long" OR TYPE STREQUAL "int64" OR TYPE STREQUAL "int53")
        set(${CPP_VAR} "int64_t" PARENT_SCOPE)
        set(${STORE_VAR} "store_int64" PARENT_SCOPE)
        set(${FETCH_VAR} "fetch_int64" PARENT_SCOPE)
    elseif(TYPE STREQUAL "int256")
        set(${CPP_VAR} "bytes::array<32>" PARENT_SCOPE)
        set(${STORE_VAR} "store_int256" PARENT_SCOPE)
        set(${FETCH_VAR} "fetch_int256" PARENT_SCOPE)
    elseif(TYPE STREQUAL "int512")
        set(${CPP_VAR} "bytes::array<64>" PARENT_SCOPE)
        set(${STORE_VAR} "store_int512" PARENT_SCOPE)
        set(${FETCH_VAR} "fetch_int512" PARENT_SCOPE)
    elseif(TYPE STREQUAL "bytes")
        set(${CPP_VAR} "bytes::binary" PARENT_SCOPE)
        set(${STORE_VAR} "store_bytes" PARENT_SCOPE)
        set(${FETCH_VAR} "fetch_bytes" PARENT_SCOPE)
    elseif(TYPE STREQUAL "string")
        set(${CPP_VAR} "std::string" PARENT_SCOPE)
        set(${STORE_VAR} "store_string" PARENT_SCOPE)
        set(${FETCH_VAR} "fetch_string" PARENT_SCOPE)
    else()
        resolve_type("${TYPE}" cpp)
        set(${CPP_VAR} "${cpp}" PARENT_SCOPE)
        set(${STORE_VAR} "BOXED" PARENT_SCOPE)
        set(${FETCH_VAR} "BOXED" PARENT_SCOPE)
    endif()
endfunction()

function(emit_struct NAME)
    cpp_name("${NAME}" qualified namespace short)
    set(members "")
    set(body "")
    set(fetch "")
    set(flags_method FALSE)
    set(flags_field "")
    set(method_body "")
    set(fields "${CONSTRUCTOR_${NAME}_FIELDS}")

    if(fields MATCHES "(^| )[A-Za-z0-9_]+:#($| )")
        set(flags_method TRUE)
    endif()

    if(NOT fields STREQUAL "")
        string(REPLACE " " ";" flist "${fields}")
        foreach(f ${flist})
            string(REGEX MATCH "^([A-Za-z0-9_]+):(.+)$" _ "${f}")
            string(TOLOWER "${CMAKE_MATCH_1}" fn)
            set(ft "${CMAKE_MATCH_2}")

            if(ft STREQUAL "#")
                set(flags_field "${fn}")
                string(APPEND body "  w.store_int32(${fn}());\n")
                string(APPEND fetch "  const int32_t ${fn} = r.fetch_int32();\n")
                continue()
            endif()

            if(ft MATCHES "^flags\\.([0-9]+)\\?(.+)$")
                set(bit "${CMAKE_MATCH_1}")
                set(inner "${CMAKE_MATCH_2}")
                math(EXPR mask_val "1 << ${bit}")
                if(inner STREQUAL "true")
                    string(APPEND members "  bool ${fn}{};\n")
                    string(APPEND method_body "  if (${fn}) {\n    result |= ${mask_val};\n  }\n")
                    string(APPEND fetch "  out.${fn} = (${flags_field} & ${mask_val}) != 0;\n")
                    continue()
                endif()
                base_map("${inner}" cpp_type sv fv)
                if(sv STREQUAL "BOXED")
                    relative_name("${cpp_type}" "${namespace}" cpp_type)
                endif()
                string(APPEND members "  std::optional<${cpp_type}> ${fn};\n")
                string(APPEND method_body "  if (${fn}) {\n    result |= ${mask_val};\n  }\n")
                if(sv STREQUAL "BOXED")
                    string(APPEND body "  if (${fn}) {\n    ${fn}->store_boxed(w);\n  }\n")
                    string(APPEND fetch "  if (${flags_field} & ${mask_val}) {\n    out.${fn} = ${cpp_type}::fetch_boxed(r);\n  }\n")
                else()
                    if(sv STREQUAL "store_bytes")
                        string(APPEND body "  if (${fn}) {\n    w.store_bytes(bytes::view(*${fn}));\n  }\n")
                    else()
                        string(APPEND body "  if (${fn}) {\n    w.${sv}(*${fn});\n  }\n")
                    endif()
                    string(APPEND fetch "  if (${flags_field} & ${mask_val}) {\n    out.${fn} = r.${fv}();\n  }\n")
                endif()
                continue()
            endif ()

            if(ft MATCHES "^vector<(.+)>$")
                set(inner "${CMAKE_MATCH_1}")
                base_map("${inner}" cpp_type sv fv)
                if(sv STREQUAL "BOXED")
                    relative_name("${cpp_type}" "${namespace}" cpp_type)
                endif()
                string(APPEND members "  std::vector<${cpp_type}> ${fn};\n")
                string(APPEND body "  w.store_vector_size(static_cast<uint32_t>(${fn}.size()));\n")
                if(sv STREQUAL "BOXED")
                    string(APPEND body "  for (const auto& item : ${fn}) {\n    item.store_boxed(w);\n  }\n")
                elseif(sv STREQUAL "store_bytes")
                    string(APPEND body "  for (const auto& item : ${fn}) {\n    w.store_bytes(bytes::view(item));\n  }\n")
                else()
                    string(APPEND body "  for (const auto& item : ${fn}) {\n    w.${sv}(item);\n  }\n")
                endif()
                string(APPEND fetch "  const auto ${fn}_count = r.fetch_vector_size();\n")
                if(sv STREQUAL "BOXED")
                    string(APPEND fetch "  for (uint32_t ${fn}_i = 0; ${fn}_i < ${fn}_count && r.ok(); ++${fn}_i) {\n    out.${fn}.push_back(${cpp_type}::fetch_boxed(r));\n  }\n")
                else()
                    string(APPEND fetch "  for (uint32_t ${fn}_i = 0; ${fn}_i < ${fn}_count && r.ok(); ++${fn}_i) {\n    out.${fn}.push_back(r.${fv}());\n  }\n")
                endif()
                continue()
            endif ()

            base_map("${ft}" cpp_type sv fv)
            if(sv STREQUAL "BOXED")
                relative_name("${cpp_type}" "${namespace}" cpp_type)
                string(APPEND members "  ${cpp_type} ${fn};\n")
                string(APPEND body "  ${fn}.store_boxed(w);\n")
                string(APPEND fetch "  out.${fn} = ${cpp_type}::fetch_boxed(r);\n")
            else()
                string(APPEND members "  ${cpp_type} ${fn}{};\n")
                if(sv STREQUAL "store_bytes")
                    string(APPEND body "  w.store_bytes(bytes::view(${fn}));\n")
                else()
                    string(APPEND body "  w.${sv}(${fn});\n")
                endif()
                string(APPEND fetch "  out.${fn} = r.${fv}();\n")
            endif()
        endforeach ()
    endif ()

    set(store_body "${body}")

    if(flags_method)
        string(APPEND members "  [[nodiscard]] int32_t ${flags_field}() const;\n")
    endif()

    if(store_body STREQUAL "")
        set(store_param "tl::TlWriter&")
    else()
        set(store_param "tl::TlWriter& w")
    endif()
    if(fetch STREQUAL "")
        set(fetch_param "tl::TlReader&")
    else()
        set(fetch_param "tl::TlReader& r")
    endif()

    set(def "struct ${short} {\n")
    string(APPEND def "  static constexpr int32_t kID = static_cast<int32_t>(${CONSTRUCTOR_${NAME}_ID});\n")
    string(APPEND def "${members}")
    string(APPEND def "  bool operator==(const ${short}&) const = default;\n")
    string(APPEND def "  void store(${store_param}) const;\n")
    string(APPEND def "  void store_boxed(tl::TlWriter& w) const;\n")
    string(APPEND def "  static ${short} fetch(${fetch_param});\n")
    string(APPEND def "  static ${short} fetch_boxed(tl::TlReader& r);\n")
    string(APPEND def "};\n")
    set(OUT_DEF "${def}" PARENT_SCOPE)
    set(OUT_NAMESPACE "${namespace}" PARENT_SCOPE)

    set(src "")
    if(flags_method)
        string(APPEND src "int32_t ${short}::${flags_field}() const {\n  int32_t result = 0;\n${method_body}  return result;\n}\n\n")
    endif()
    string(APPEND src "void ${short}::store(${store_param}) const {\n${store_body}}\n\n")
    string(APPEND src "void ${short}::store_boxed(tl::TlWriter& w) const {\n  w.store_int32(kID);\n  store(w);\n}\n\n")
    string(APPEND src "${short} ${short}::fetch(${fetch_param}) {\n  ${short} out;\n${fetch}  return out;\n}\n\n")
    string(APPEND src "${short} ${short}::fetch_boxed(tl::TlReader& r) {\n  if (r.fetch_int32() != kID) {\n    r.set_error();\n    return {};\n  }\n  return fetch(r);\n}\n")
    set(OUT_SRC "${src}" PARENT_SCOPE)
endfunction()

function(emit_variant RESULT)
    cpp_name("${RESULT}" wrapper_qualified wrapper_namespace wrapper_short)
    set(constructors "${RES_${RESULT}_CONSTRUCTORS}")
    set(types "")
    set(cases "")
    foreach(c ${constructors})
        cpp_name("${c}" c_qualified c_namespace c_short)
        relative_name("${c_qualified}" "${wrapper_namespace}" c_rel)
        if(types STREQUAL "")
            set(types "${c_rel}")
        else()
            string(APPEND types ", ${c_rel}")
        endif()
        string(APPEND cases "    case ${c_rel}::kID:\n      out.value = ${c_rel}::fetch(r);\n      break;\n")
    endforeach()
    set(def "struct ${wrapper_short} {\n  std::variant<${types}> value;\n")
    string(APPEND def "  bool operator==(const ${wrapper_short}&) const = default;\n")
    string(APPEND def "  void store_boxed(tl::TlWriter& w) const;\n")
    string(APPEND def "  static ${wrapper_short} fetch_boxed(tl::TlReader& r);\n};\n")
    set(OUT_DEF "${def}" PARENT_SCOPE)
    set(OUT_NAMESPACE "${wrapper_namespace}" PARENT_SCOPE)
    set(src "")
    string(APPEND src "void ${wrapper_short}::store_boxed(tl::TlWriter& w) const {\n")
    string(APPEND src "  std::visit([&w](const auto& v) {\n    v.store_boxed(w);\n  }, value);\n}\n\n")
    string(APPEND src "${wrapper_short} ${wrapper_short}::fetch_boxed(tl::TlReader& r) {\n  ${wrapper_short} out;\n  switch (r.fetch_int32()) {\n${cases}    default:\n      r.set_error();\n      break;\n  }\n  return out;\n}\n")
    set(OUT_SRC "${src}" PARENT_SCOPE)
endfunction()

macro(namespace_seen NAMESPACE LIST_VAR)
    list(FIND ${LIST_VAR} "${NAMESPACE}" namespace_idx)
    if(namespace_idx EQUAL -1)
        list(APPEND ${LIST_VAR} "${NAMESPACE}")
    endif()
endmacro()

function(namespace_indent DEPTH OUT_VAR)
    math(EXPR n "${DEPTH} * 2")
    if(n GREATER 0)
        string(REPEAT " " ${n} s)
    else()
        set(s "")
    endif()
    set(${OUT_VAR} "${s}" PARENT_SCOPE)
endfunction()

macro(close_groups KEEP)
    list(LENGTH open_parts ol)
    while(ol GREATER ${KEEP})
        list(LENGTH open_groups ng)
        math(EXPR last "${ng} - 1")
        list(GET open_groups ${last} grp)
        namespace_indent(${last} ind)
        string(APPEND acc "${ind}} // namespace ${grp}\n")
        list(REMOVE_AT open_groups ${last})
        string(REPLACE "::" ";" grp_parts "${grp}")
        list(LENGTH grp_parts gpc)
        while(gpc GREATER 0)
            list(LENGTH open_parts opl)
            math(EXPR li "${opl} - 1")
            list(REMOVE_AT open_parts ${li})
            math(EXPR gpc "${gpc} - 1")
        endwhile()
        list(LENGTH open_parts ol)
    endwhile()
endmacro()

function(assemble OUT_VAR ORDER PREFIX ROOT)
    set(acc "")
    set(open_groups "")
    set(open_parts "")
    foreach(namespace ${ORDER})
        if(namespace STREQUAL "")
            set(full "${ROOT}")
        elseif(ROOT STREQUAL "")
            set(full "${namespace}")
        else()
            set(full "${ROOT}::${namespace}")
        endif()
        string(REPLACE "::" ";" want "${full}")
        list(LENGTH open_parts ol)
        list(LENGTH want wl)

        set(common 0)
        set(i 0)
        while(i LESS ol AND i LESS wl)
            list(GET open_parts ${i} a)
            list(GET want ${i} b)
            if(NOT a STREQUAL b)
                break()
            endif()
            math(EXPR common "${common} + 1")
            math(EXPR i "${i} + 1")
        endwhile()

        close_groups(${common})

        list(LENGTH open_parts open_now)
        if(open_now LESS wl)
            set(joined "")
            set(k ${open_now})
            while(k LESS wl)
                list(GET want ${k} part)
                if(joined STREQUAL "")
                    set(joined "${part}")
                else()
                    string(APPEND joined "::${part}")
                endif()
                list(APPEND open_parts "${part}")
                math(EXPR k "${k} + 1")
            endwhile()
            list(LENGTH open_groups depth)
            namespace_indent(${depth} ind)
            if(NOT acc STREQUAL "")
                string(APPEND acc "\n")
            endif()
            string(APPEND acc "${ind}namespace ${joined} {\n")
            list(APPEND open_groups "${joined}")
        endif()

        string(REPLACE "::" "__" sanitized "${namespace}")
        set(content "${${PREFIX}_${sanitized}}")
        string(REGEX REPLACE "[ \t\r\n]+$" "" content "${content}")
        list(LENGTH open_groups depth)
        namespace_indent(${depth} bind)
        if(NOT bind STREQUAL "")
            string(REPLACE "\n" "\n${bind}" content "${content}")
        endif()
        string(APPEND acc "${bind}${content}\n")
    endforeach()

    close_groups(0)

    string(REGEX REPLACE "[ \t]+\n" "\n" acc "${acc}")
    set(${OUT_VAR} "${acc}" PARENT_SCOPE)
endfunction()

set(DEF_NAMESPACES_ORDER "")
foreach(r ${RESULT_TYPES})
    set(constructors "${RES_${r}_CONSTRUCTORS}")
    list(LENGTH constructors count)

    foreach(constructor ${constructors})
        emit_struct("${constructor}")
        string(REPLACE "::" "__" sanitized "${OUT_NAMESPACE}")
        namespace_seen("${OUT_NAMESPACE}" DEF_NAMESPACES_ORDER)
        string(APPEND "DEF_NAMESPACE_${sanitized}" "${OUT_DEF}\n")
        string(APPEND "SRC_NAMESPACE_${sanitized}" "${OUT_SRC}\n")
    endforeach ()

    if(count GREATER 1)
        emit_variant("${r}")
        string(REPLACE "::" "__" sanitized "${OUT_NAMESPACE}")
        namespace_seen("${OUT_NAMESPACE}" DEF_NAMESPACES_ORDER)
        string(APPEND "DEF_NAMESPACE_${sanitized}" "${OUT_DEF}\n")
        string(APPEND "SRC_NAMESPACE_${sanitized}" "${OUT_SRC}\n")
    endif()
endforeach ()

assemble(HEADER "${DEF_NAMESPACES_ORDER}" DEF_NAMESPACE ntgcalls)
assemble(SRC "${DEF_NAMESPACES_ORDER}" SRC_NAMESPACE ntgcalls)

set(E2E_BANNER "// Auto-generated from TDLib's e2e_api.tl. DO NOT EDIT.\n//\n// Source:  https://github.com/tdlib/td/blob/${E2E_TL_COMMIT}/td/generate/scheme/e2e_api.tl\n// Schema:  td@${e2e_tl_short}\n\n")

file(WRITE "${E2E_HEADER_DIR}"
        "${E2E_BANNER}#pragma once\n#include <array>\n#include <cstdint>\n#include <optional>\n#include <string>\n#include <variant>\n#include <vector>\n#include <ntgcalls/tl/tl.hpp>\n\n${HEADER}")
file(WRITE "${E2E_SRC_DIR}"
        "${E2E_BANNER}#include <ntgcalls/tl/e2e_api.hpp>\n\n${SRC}")

set(E2E_LAST_GEN_COMMIT "${E2E_TL_COMMIT}" CACHE STRING "Last e2e code generation" FORCE)
