set(WEBRTC_PATCH_LOCATION ${WEBRTC_DIR}/patches/${WEBRTC_PATCH_FILE})
if(NOT DEFINED LAST_WEBRTC_REVISION OR NOT ${LAST_WEBRTC_REVISION} STREQUAL ${WEBRTC_REVISION} OR NOT EXISTS ${WEBRTC_PATCH_LOCATION})
    message(STATUS "Downloading patch file for ${WEBRTC_REVISION} revision")
    GitFile(
        URL ${WEBRTC_PATCH_URL}
        DIRECTORY ${WEBRTC_PATCH_LOCATION}
    )
    set(LAST_WEBRTC_REVISION ${WEBRTC_REVISION} CACHE STRING "Last patch revision" FORCE)
endif ()