set(cmake_dir ${CMAKE_SOURCE_DIR}/cmake)
function(setup_platform_libs target_name)
    if (WINDOWS)
        include(${cmake_dir}/Windows.cmake)
    elseif(LINUX)
        include(${cmake_dir}/Linux.cmake)
    elseif(MACOS)
        include(${cmake_dir}/macOS.cmake)
    else()
        message(FATAL_ERROR "${CMAKE_SYSTEM_NAME} with ${CMAKE_HOST_SYSTEM_PROCESSOR} is not supported yet")
    endif()
endfunction()