name: Build And Publish
permissions:
  contents: read
on:
  workflow_dispatch:
    inputs:
      use-blacksmith:
        description: 'Use Blacksmith runners (faster builds)'
        required: false
        default: false
        type: boolean
      build-shared-libs:
        description: 'Build shared libraries'
        required: false
        default: true
        type: boolean
      build-static-libs:
        description: 'Build static libraries'
        required: false
        default: true
        type: boolean
      build-wheels:
        description: 'Build wheels'
        required: false
        default: false
        type: boolean
      linux-build:
        description: 'Build for Linux'
        required: false
        default: true
        type: boolean
      linux-arm64-build:
        description: 'Build for Linux ARM64'
        required: false
        default: true
        type: boolean
      macos-build:
        description: 'Build for macOS'
        required: false
        default: false
        type: boolean
      windows-build:
        description: 'Build for Windows'
        required: false
        default: false
        type: boolean
      android-build:
        description: 'Build for Android'
        required: false
        default: false
        type: boolean
      publish:
        description: 'Publish the library'
        required: false
        default: true
        type: boolean
jobs:
  setup:
    name: Generate Build Matrix
    runs-on: ubuntu-latest
    outputs:
      desktop-matrix: ${{ steps.set-matrix.outputs.desktop-matrix }}
      mobile-matrix: ${{ steps.set-matrix.outputs.mobile-matrix }}
      has-desktop: ${{ steps.set-matrix.outputs.has-desktop }}
      has-mobile: ${{ steps.set-matrix.outputs.has-mobile }}
    steps:
      - name: Set matrix
        id: set-matrix
        run: |
          desktop_list=""
          if [[ "${{ github.event.inputs.linux-build }}" == "true" ]]; then
            desktop_list+=",{\"os\":\"ubuntu-latest\",\"blacksmith_os\":\"blacksmith-4vcpu-ubuntu-2404\",\"shared_name\":\"linux-x86_64\",\"cibw_os_build\":\"manylinux_\",\"container_image\":\"ghcr.io/pytgcalls/ntgcalls/manylinux-x86_64:latest\"}"
          fi
          if [[ "${{ github.event.inputs.linux-arm64-build }}" == "true" ]]; then
            desktop_list+=",{\"os\":\"arm64-server\",\"blacksmith_os\":\"blacksmith-4vcpu-ubuntu-2404-arm\",\"shared_name\":\"linux-arm64\",\"cibw_os_build\":\"manylinux_\",\"container_image\":\"ghcr.io/pytgcalls/ntgcalls/manylinux-arm64:latest\"}"
          fi
          if [[ "${{ github.event.inputs.macos-build }}" == "true" ]]; then
            desktop_list+=",{\"os\":\"macos-15\",\"blacksmith_os\":\"blacksmith-6vcpu-macos-15\",\"shared_name\":\"macos-arm64\",\"cibw_os_build\":\"macosx_\"}"
          fi
          if [[ "${{ github.event.inputs.windows-build }}" == "true" ]]; then
            desktop_list+=",{\"os\":\"windows-2022\",\"blacksmith_os\":\"blacksmith-4vcpu-windows-2025\",\"shared_name\":\"windows-x86_64\"}"
          fi
          [[ -n "$desktop_list" ]] && desktop_list="${desktop_list:1}"
          echo "desktop-matrix={\"include\":[$desktop_list]}" >> $GITHUB_OUTPUT
          
          mobile_list=""
          if [[ "${{ github.event.inputs.android-build }}" == "true" ]]; then
            mobile_list+=",{\"os\":\"ubuntu-latest\",\"blacksmith_os\":\"blacksmith-4vcpu-ubuntu-2404\",\"shared_name\":\"android\"}"
          fi
          [[ -n "$mobile_list" ]] && mobile_list="${mobile_list:1}"
          echo "mobile-matrix={\"include\":[$mobile_list]}" >> $GITHUB_OUTPUT
          
          [[ -n "$desktop_list" ]] && echo "has-desktop=true" >> $GITHUB_OUTPUT || echo "has-desktop=false" >> $GITHUB_OUTPUT
          [[ -n "$mobile_list"  ]] && echo "has-mobile=true"  >> $GITHUB_OUTPUT || echo "has-mobile=false"  >> $GITHUB_OUTPUT

  build-desktop:
    name: Build (${{ matrix.shared_name }}) [${{ inputs.use-blacksmith == true && 'Blacksmith' || 'GitHub' }}]
    if: |
        needs.setup.outputs.has-desktop == 'true' &&
        (
            github.event.inputs.build-wheels == 'true' || 
            github.event.inputs.build-shared-libs == 'true' || 
            github.event.inputs.build-static-libs == 'true'
        )
    needs: setup
    runs-on: ${{ inputs.use-blacksmith == true && matrix.blacksmith_os || matrix.os }}
    container:
      image: ${{ matrix.container_image }}
    permissions:
      contents: read
    strategy:
      matrix: ${{fromJson(needs.setup.outputs.desktop-matrix)}}

    steps:
      - name: Check out the repo
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v6
        if: ${{ !(startsWith(matrix.shared_name, 'linux')) }}
        id: python-setup
        with:
          python-version: "3.10 - 3.14"

      - name: Resolve Python path
        id: python
        run: |
          if [[ -n "${{ steps.python-setup.outputs.python-path }}" ]]; then
            echo "path=${{ steps.python-setup.outputs.python-path }}" >> $GITHUB_OUTPUT
          else
            echo "path=python3" >> $GITHUB_OUTPUT
          fi
        shell: bash

      - name: Install Python Requirements
        run: |
          "${{ steps.python.outputs.path }}" -m pip install cibuildwheel setuptools
        shell: bash

      - name: Build Shared Libs
        if: github.event.inputs.build-shared-libs == 'true'
        run: |
          ${{ steps.python.outputs.path }} setup.py build_lib

      - name: Build Static Libs
        if: github.event.inputs.build-static-libs == 'true'
        run: |
          ${{ steps.python.outputs.path }} setup.py build_lib --static

      - name: Upload Shared Libs for ${{ matrix.shared_name }}
        uses: actions/upload-artifact@v7
        if: github.event.inputs.build-shared-libs == 'true'
        with:
          name: ntgcalls.${{ matrix.shared_name }}-shared_libs
          path: ./shared-output/*
          if-no-files-found: error

      - name: Upload Static Libs for ${{ matrix.shared_name }}
        uses: actions/upload-artifact@v7
        if: github.event.inputs.build-static-libs == 'true'
        with:
          name: ntgcalls.${{ matrix.shared_name }}-static_libs
          path: ./static-output/*
          if-no-files-found: error

      - name: Build wheels
        run: ${{ steps.python.outputs.path }} -m cibuildwheel --output-dir wheelhouse
        if: github.event.inputs.build-wheels == 'true'
        env:
          CIBW_PROJECT_REQUIRES_PYTHON: ">=3.10"
          CIBW_BUILD: cp3*-${{ matrix.cibw_os_build }}*
          CIBW_TEST_COMMAND: python -m unittest discover -s {package}/tests
          CIBW_MANYLINUX_AARCH64_IMAGE: ghcr.io/pytgcalls/ntgcalls/manylinux-arm64:latest
          CIBW_MANYLINUX_X86_64_IMAGE: ghcr.io/pytgcalls/ntgcalls/manylinux-x86_64:latest
          CIBW_MUSLLINUX_X86_64_IMAGE: ghcr.io/pytgcalls/ntgcalls/musllinux-x86_64:latest
          CIBW_ENVIRONMENT: "PYPI_TAGS=1"
          MACOSX_DEPLOYMENT_TARGET: 14.0

      - uses: actions/upload-artifact@v7
        if: github.event.inputs.build-wheels == 'true'
        with:
          name: ntgcalls-${{ matrix.shared_name }}-wheels
          path: ./wheelhouse/*.whl
          if-no-files-found: error

  build-mobile:
    name: Build (${{ matrix.shared_name }}) [${{ inputs.use-blacksmith == true && 'Blacksmith' || 'GitHub' }}]
    if: needs.setup.outputs.has-mobile == 'true'
    needs: setup
    runs-on: ${{ inputs.use-blacksmith == true && matrix.blacksmith_os || matrix.os }}
    permissions:
      contents: read
      packages: write
    strategy:
      matrix: ${{fromJson(needs.setup.outputs.mobile-matrix)}}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v6
        id: python
        with:
          python-version: "3.14"

      - name: Install Python Requirements
        run: |
          "${{ steps.python.outputs.python-path }}" -m pip install setuptools
          "${{ steps.python.outputs.python-path }}" -m pip install pipx
        shell: bash

      - name: Build JNI Libraries
        run: |
          ${{ steps.python.outputs.python-path }} setup.py build_lib --android
        shell: bash

      - name: Set up Maven Central Repository
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: central

      - name: Publish Library to Maven Central
        run: bash ./gradlew publishAndReleaseToMavenCentral --no-configuration-cache
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.CENTRAL_TOKEN_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.CENTRAL_TOKEN_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.GPG_SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.GPG_SIGNING_KEY_PASSWORD }}
        shell: bash
        working-directory: android/


  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: [ build-desktop ]
    if: github.event.inputs.publish == 'true'
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Get library Version
        id: get-library-version
        run: |
          VERSION=$(grep -oP -m 1 'ntgcalls VERSION \K[A-Za-z0-9.]+' CMakeLists.txt)
          echo "Library Version: $VERSION"
          echo "raw_version=$VERSION" >> $GITHUB_OUTPUT

      - name: Patch version number
        id: patch-version
        run: |
          version="${{ steps.get-library-version.outputs.raw_version }}"
          fancy_version="$(cmake -DPROJECT_VERSION="$version" -DGITHUB_TAGS=ON -P cmake/VersionUtil.cmake 2>&1)"
          is_dev=false
          [[ "$version" == *.*.*.* ]] && is_dev=true
          {
            echo "version=$fancy_version"
            echo "is_dev=$is_dev"
          } >> "$GITHUB_OUTPUT"

      - name: Download artifacts
        uses: actions/download-artifact@v8
        with:
          path: tmp/

      - name: Prepare source distribution
        if: github.event.inputs.build-wheels == 'true'
        run: |
          python3 -m pip install --upgrade setuptools
          python3 setup.py sdist
        env:
          PYPI_TAGS: 1

      - name: Zip releases
        run: |
          mkdir releases
          for dir in tmp/*_libs; do
            if [ -d "$dir" ]; then
              echo "$dir"
              folder_name=$(basename "$dir" .zip)
              (cd $dir && zip -r "../../releases/${folder_name}.zip" *)
            fi
          done

      - name: Create Release
        id: create-new-release
        uses: softprops/action-gh-release@v3
        with:
          files: |
            ./releases/*
          tag_name: "v${{ steps.patch-version.outputs.version }}"
          name: "NTgCalls auto build v${{ steps.patch-version.outputs.version }}"
          body: "These are the build files for the commit [${{ github.sha }}](https://github.com/${{ github.repository }}/commit/${{ github.sha }}).\nThese files were built during [this workflow run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})."
          prerelease: ${{ steps.patch-version.outputs.is_dev }}

      - name: Extract artifacts
        run: find tmp -type f -name "*.whl" | xargs -I {} mv {} dist

      - name: Publish a Python distribution to PyPI.
        if: github.event.inputs.build-wheels == 'true'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true
          packages-dir: dist/
